Repository rear/rear, pull requests merged in 2018-12, with the labels that each got.

#1992 Include UDF support in rescue ISO when backup is stored on the ISO itself
  usr/share/rear/conf/default.conf
  usr/share/rear/output/ISO/Linux-i386/810_prepare_multiple_iso.sh
  usr/share/rear/output/ISO/Linux-i386/820_create_iso_image.sh
  usr/share/rear/output/ISO/Linux-ia64/800_create_isofs.sh
  usr/share/rear/output/ISO/Linux-ppc64le/820_create_iso_image.sh
  usr/share/rear/prep/ISO/GNU/Linux/320_verify_mkisofs.sh
Labels: enhancement

#1993 Automatically exclude $BUILD_DIR from the backup
  usr/sbin/rear
  usr/share/rear/conf/default.conf
Labels: minor bug

#1995 NBU: exclude '/usr/openv/netbackup/baremetal' which is not needed
  usr/share/rear/conf/default.conf
Labels: cleanup

#1987 Fix for issue https://github.com/rear/rear/issues/1986
  usr/share/rear/skel/default/etc/scripts/system-setup.d/58-start-dhclient.sh
Labels: bug

#1997 $TMP_DIR parent directory was missing before initrd filename variable.
  usr/share/rear/output/ISO/Linux-ppc64le/800_create_isofs.sh
Labels: bug

#1978 Fix for 'error:unrecognized number' when booting ISO on PPC
  usr/share/rear/output/ISO/Linux-ppc64/310_create_grub2.sh
  usr/share/rear/output/ISO/Linux-ppc64le/300_create_grub2.sh
Labels: enhancement

#2004 network: Automatically map device to its new name when device is found on the system with same MAC address but different name
  usr/share/rear/skel/default/etc/scripts/system-setup.d/55-migrate-network-devices.sh
Labels: bug, enhancement

#2005 Provide final power to the user for mkfs.xfs options if needed (issue 1998)
  usr/share/rear/conf/default.conf
  usr/share/rear/layout/prepare/GNU/Linux/130_include_filesystem_code.sh
Labels: enhancement

#2001 fedora29 grub2-efi-x64-modules does not contain linuxefi module
  usr/share/rear/lib/uefi-functions.sh
Labels: minor bug
