Repository rear/rear, pull requests merged in 2018-10, with the labels that each got.

#1920 Check if CONFIG_DIR is not a file #1815
  usr/sbin/rear
Labels: enhancement

#1922 avoid nullglob pitfalls in 250_populate_efibootimg.sh (issue #1921) and generally overhalued that script
  usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh
Labels: cleanup, enhancement

#1935 Avoid find in whole fstree in 500 clone keyboard mappings issue1906
  usr/share/rear/rescue/GNU/Linux/500_clone_keyboard_mappings.sh
Labels: bug

#1934 Fix for #1926 - Restore fails when teaming runner is configured as LACP
  tests/setup1/README
  tests/setup1/etc/sysconfig/network-scripts/ifcfg-eth11
  tests/setup1/etc/sysconfig/network-scripts/ifcfg-eth12
  tests/setup1/etc/sysconfig/network-scripts/ifcfg-team1112
  tests/setup1/etc/sysconfig/network-scripts/route-team1112
  tests/setup1/kvm.xml
  tests/setup1/mappings/ip_addresses
  tests/setup1/run.sh
  tests/setup1/tcase1.sh
  tests/setup1/tcase1_results/ip_a.expected
  tests/setup1/tcase1_results/ip_r.expected
  tests/setup1/tcase2.sh
  tests/setup1/tcase2_results/ip_a.expected
  tests/setup1/tcase2_results/ip_r.expected
  tests/setup1/tcase3.sh
  tests/setup1/tcase3_results/ip_a.expected
  tests/setup1/tcase3_results/ip_r.expected
  tests/setup1/tcase4.sh
  tests/setup1/tcase4_results/ip_a.expected
  tests/setup1/tcase4_results/ip_r.expected
  tests/setup1/tcase5.sh
  tests/setup1/tcase5_results/ip_a.expected
  tests/setup1/tcase5_results/ip_r.expected
  tests/setup1/tcase6.sh
  tests/setup1/tcase6_results/ip_a.expected
  tests/setup1/tcase6_results/ip_r.expected
  tests/setup1/tcase7.sh
  tests/setup1/tcase7_results/ip_a.expected
  tests/setup1/tcase7_results/ip_r.expected
  tests/setup1/tcase8.sh
  tests/setup1/tcase8_results/ip_a.expected
  tests/setup1/tcase8_results/ip_r.expected
  tests/setup1/verify.sh
  tests/setup2/README
  tests/setup2/tcase1.sh
  tests/setup2/tcase1_results/ip_a.expected
  tests/setup2/tcase2.sh
  tests/setup2/tcase2_results/ip_a.expected
  tests/setup2/tcase3.sh
  tests/setup2/tcase3_results/ip_a.expected
  tests/setup2/tcase4.sh
  tests/setup2/tcase4_results/ip_a.expected
  tests/setup2/tcase5.sh
  tests/setup2/tcase5_results/ip_a.expected
  tests/setup2/tcase6.sh
  tests/setup2/tcase6_results/ip_a.expected
  tests/setup2/tcase7.sh
  tests/setup2/tcase7_results/ip_a.expected
  tests/setup2/tcase8.sh
  tests/setup2/tcase8_results/ip_a.expected
  usr/share/rear/conf/default.conf
  usr/share/rear/rescue/GNU/Linux/310_network_devices.sh
Labels: enhancement

#1940 Support simulation mode for dump and help workflows plus better help workflow
  usr/share/rear/init/default/050_check_rear_recover_mode.sh
  usr/share/rear/lib/dump-workflow.sh
  usr/share/rear/lib/finalizeonly-workflow.sh
  usr/share/rear/lib/help-workflow.sh
  usr/share/rear/lib/opaladmin-workflow.sh
  usr/share/rear/lib/udev-workflow.sh
Labels: enhancement, minor bug

#1937 Remove After=syslog.target form dbus.service #1230
  usr/share/rear/skel/default/usr/lib/systemd/system/dbus.service
Labels: cleanup, enhancement

#1943 properly handle module-less kernels (fixes #1941)
  usr/share/rear/lib/linux-functions.sh
Labels: enhancement, minor bug

#1947 Enhance and cleanup 985_fix_broken_links.sh (issue 1638 and pull request 1734)
  usr/share/rear/build/default/985_fix_broken_links.sh
Labels: bug, enhancement
