Repository rear/rear, pull requests merged in 2018-11, with the labels that each got.

#1954 network: Record permanent mac address when device is enslaved in a bond, or else /etc/mac-addresses will record broken information
  usr/share/rear/rescue/GNU/Linux/310_network_devices.sh
Labels: bug

#1961 moved PROGS from GNU/Linux.conf to default.conf REQUIRED_PROGS #892
  usr/share/rear/conf/GNU/Linux.conf
  usr/share/rear/conf/default.conf
Labels: cleanup, enhancement

#1962 cleanup REQUIRED_PROGS checks (issue 892)
  usr/sbin/rear
  usr/share/rear/build/default/950_check_missing_programs.sh
  usr/share/rear/build/default/980_verify_rootfs.sh
  usr/share/rear/init/default/950_check_missing_programs.sh
  usr/share/rear/prep/default/950_check_missing_programs.sh
Labels: cleanup, enhancement, minor bug

#1964 Add specific required programs to REQUIRED_PROGS (issue 1963)
  usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
  usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh
  usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh
  usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
  usr/share/rear/layout/save/GNU/Linux/240_swaps_layout.sh
  usr/share/rear/layout/save/GNU/Linux/250_drbd_layout.sh
  usr/share/rear/layout/save/GNU/Linux/260_crypt_layout.sh
  usr/share/rear/layout/save/GNU/Linux/270_hpraid_layout.sh
  usr/share/rear/layout/save/GNU/Linux/280_multipath_layout.sh
Labels: bug, enhancement

#1969 check for carriage return in {local|site|rescue}.conf files
  usr/sbin/rear
Labels: enhancement

#1976 Issue #1975 - Missing libraries in Rescue ISO causing executables to fail
  usr/share/rear/build/GNU/Linux/100_copy_as_is.sh
Labels: bug

#1971 Add /etc/ca-certificates directory to ReaR recovery system for Arch Linux
  usr/share/rear/conf/GNU/Linux.conf
Labels: enhancement

#1979 Fix broken 'make pacman'
  Makefile
  packaging/arch/PKGBUILD.local
Labels: minor bug

#1980 Fix for #1974 - NBU (Netbackup) not working since ReaR 2.4
  usr/share/rear/build/GNU/Linux/100_copy_as_is.sh
  usr/share/rear/build/GNU/Linux/390_copy_binaries_libraries.sh
  usr/share/rear/build/OPALPBA/Linux-i386/391_list_executable_dependencies.sh
  usr/share/rear/build/default/980_verify_rootfs.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/_input-output-functions.sh
  usr/share/rear/lib/linux-functions.sh
  usr/share/rear/prep/NBU/default/450_check_nbu_client_configured.sh
Labels: bug, enhancement

#1977 Ignore relabeling of /boot/efi only if directory exists.
  usr/share/rear/restore/NETFS/Linux-i386/510_selinux_fixfiles_exclude_dirs.sh
Labels: cleanup, enhancement, minor bug

#1981 Rearranged final build stage scripts so that "verify_rootfs" runs after "fix_broken_links"
  usr/sbin/rear
  usr/share/rear/build/default/975_update_os_conf.sh
  usr/share/rear/build/default/985_fix_broken_links.sh
  usr/share/rear/build/default/990_verify_rootfs.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/sesam-functions.sh
Labels: cleanup, minor bug

#1985 Cleaned up how KERNEL_FILE is set (issues 1851 and 1983)
  usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh
  usr/share/rear/output/ISO/Linux-i386/800_create_isofs.sh
  usr/share/rear/output/ISO/Linux-ia64/300_create_bootimg.sh
  usr/share/rear/output/ISO/Linux-ppc64le/800_create_isofs.sh
  usr/share/rear/output/PXE/default/800_copy_to_tftp.sh
  usr/share/rear/output/RAMDISK/Linux-i386/900_copy_ramdisk.sh
  usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
  usr/share/rear/output/default/940_grub2_rescue.sh
  usr/share/rear/output/default/940_grub_rescue.sh
  usr/share/rear/pack/Debian/ia64/300_copy_kernel.sh
  usr/share/rear/pack/Fedora/ia64/300_copy_kernel.sh
  usr/share/rear/pack/GNU/Linux/400_guess_kernel.sh
  usr/share/rear/pack/Linux-i386/300_copy_kernel.sh
  usr/share/rear/pack/Linux-ia64
  usr/share/rear/pack/Linux-ppc64/300_copy_kernel.sh
  usr/share/rear/pack/Linux-ppc64le/300_copy_kernel.sh
  usr/share/rear/prep/GNU/Linux/400_guess_kernel.sh
Labels: cleanup, minor bug

#1988 Removed file command usage in 400_guess_kernel.sh because it is not reliably working to test if a file is actually a kernel
  usr/share/rear/prep/GNU/Linux/400_guess_kernel.sh
Labels: bug
