Repository rear/rear, pull requests merged in 2018-08, with the labels that each got.

#1889 Print multipath device name during rescue when firendly_name is off
  usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh
Labels: bug

#1887 #1886 - LPAR/PPC64 bootlist is incorrectly set when having multiple 'prep' partitions
  usr/share/rear/finalize/Linux-ppc64le/680_install_PPC_bootlist.sh
Labels: bug, cleanup

#1895 Avoid false alarm during md5sum verification (related to issue1883)
  usr/share/rear/build/default/995_md5sums_rootfs.sh
  usr/share/rear/skel/default/etc/scripts/system-setup
Labels: enhancement, minor bug

#1894 Moved what script 67-check-by-label-cdrom.sh does into the mount_url function 'iso' case (issue1893)
  usr/share/rear/lib/global-functions.sh
  usr/share/rear/skel/default/etc/scripts/system-setup.d/67-check-by-label-cdrom.sh
Labels: bug, cleanup, enhancement

#1903 change the logic of the continue with function is_disk_a_pv during grub2 config
  usr/share/rear/finalize/Linux-i386/610_install_grub.sh
  usr/share/rear/finalize/Linux-i386/620_install_grub2.sh
Labels: bug

#1908 remove BuildRoot and clean section from rear.spec
  packaging/rpm/rear.spec
Labels: cleanup, enhancement
