Repository rear/rear, pull requests merged in 2018-09, with the labels that each got.

#1914 Issue #1913 - NETFS+tar backup exit code testing insufficient (may fail to catch real backup errors)
  usr/share/rear/backup/NETFS/default/500_make_backup.sh
Labels: bug

#1916 Added exclusion of zram devices from device mapping
  usr/share/rear/conf/default.conf
Labels: enhancement

#1918 Added default value (0) for crc variable (XFS).
  usr/share/rear/lib/filesystems-functions.sh
Labels: minor bug
