Repository rear/rear, pull requests merged in 2018-03, with the labels that each got.

#1740 Yum+backup
  doc/user-guide/14-ZYPPER-and-YUM.adoc
  usr/share/rear/backup/YUM/default/400_create_include_exclude_files.sh
  usr/share/rear/backup/YUM/default/500_make_backup.sh
  usr/share/rear/backup/YUM/default/600_capture_selinux_contexts.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/prep/YUM/default/050_prep_python.sh
  usr/share/rear/prep/YUM/default/200_selinux_in_use.sh
  usr/share/rear/prep/YUM/default/400_prep_yum.sh
  usr/share/rear/restore/YUM/default/403_binds_for_selinux.sh
  usr/share/rear/restore/YUM/default/405_clone_users_and_groups.sh
  usr/share/rear/restore/YUM/default/405_recreate_users_and_groups.sh
  usr/share/rear/restore/YUM/default/410_restore_backup.sh
  usr/share/rear/restore/YUM/default/600_restore_selinux_contexts.sh
  usr/share/rear/restore/YUM/default/940_generate_fstab.sh
  usr/share/rear/restore/YUM/default/950_grub2_mkconfig.sh
  usr/share/rear/restore/YUM/default/950_grub_mkconfig.sh
  usr/share/rear/verify/YUM/default/550_check_backup_archive.sh
Labels: enhancement

#1733 Replace 400_autoresize_disks by 420_autoresize_last_partitions and 430_autoresize_all_partitions
  usr/share/rear/conf/default.conf
  usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
  usr/share/rear/layout/prepare/default/010_prepare_files.sh
  usr/share/rear/layout/prepare/default/420_autoresize_last_partitions.sh
  usr/share/rear/layout/prepare/default/430_autoresize_all_partitions.sh
  usr/share/rear/layout/prepare/default/540_generate_device_code.sh
  usr/share/rear/layout/recreate/default/200_run_layout_code.sh
  usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
  usr/share/rear/layout/save/GNU/Linux/510_current_disk_usage.sh
  usr/share/rear/lib/layout-functions.sh
Labels: bug, cleanup, enhancement

#1746 Fixed 100_include_partition_code.sh regarding autoresizing partitions
  usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
Labels: bug

#1748 Run exit tasks code with default bash flags and options (issues #700 and #1747)
  usr/share/rear/lib/_input-output-functions.sh
Labels: bug

#1751 Fixed invalid reported return code (always 0) upon NBU restoration failure
  usr/share/rear/restore/NBU/default/400_restore_with_nbu.sh
Labels: minor bug

#1754 additional check for Hah!IdontNeedEFI #1752
  usr/share/rear/layout/save/default/445_guess_bootloader.sh
Labels: minor bug

#1756 Replace pstree by ps command (issue#1755)
  usr/share/rear/conf/GNU/Linux.conf
  usr/share/rear/lib/_input-output-functions.sh
Labels: minor bug

#1758 Migation mode confirmation at beginning of finalize stage
  usr/share/rear/finalize/default/020_confirm_finalize.sh
  usr/share/rear/finalize/default/050_prepare_checks.sh
Labels: Dedicated Priority Support, enhancement

#1757 exclude docker FS from layout #1749
  usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
Labels: enhancement, minor bug

#1760 Update hp_raid-functions.sh and 270_hpraid_layout.sh
  usr/share/rear/layout/save/GNU/Linux/270_hpraid_layout.sh
  usr/share/rear/lib/hp_raid-functions.sh
Labels: enhancement

#1763 unattended PXE mode with BAREOS is not unattended enough
  usr/share/rear/restore/BAREOS/default/400_restore_backup.sh
Labels: external tool, minor bug
