Repository rear/rear, pull requests merged in 2018-02, with the labels that each got.

#1729 document ReaR specific recovery system kernel options (issue 1728)
  doc/rear.8
  doc/rear.8.adoc
Labels: documentation, enhancement

#1730 ReaR with Borg back end to USB.
  doc/user-guide/04-scenarios.adoc
  usr/share/rear/backup/BORG/default/250_mount_usb.sh
  usr/share/rear/backup/BORG/default/500_make_backup.sh
  usr/share/rear/backup/BORG/default/800_prune_old_backups.sh
  usr/share/rear/backup/BORG/default/900_umount_usb.sh
  usr/share/rear/lib/borg-functions.sh
  usr/share/rear/prep/BORG/default/100_set_vars.sh
  usr/share/rear/prep/BORG/default/250_mount_usb.sh
  usr/share/rear/prep/BORG/default/300_init_archive.sh
  usr/share/rear/prep/BORG/default/900_umount_usb.sh
  usr/share/rear/restore/BORG/default/250_mount_usb.sh
  usr/share/rear/restore/BORG/default/400_restore_backup.sh
Labels: enhancement

#1737 Correction to the 650_check_iso_recoverable.sh for NSR_CLIENT_MODE
  usr/share/rear/layout/save/NSR/default/650_check_iso_recoverable.sh
Labels: external tool

#1739 430 prepare timesync.sh chronyd support
  usr/share/rear/conf/default.conf
  usr/share/rear/rescue/default/430_prepare_timesync.sh
Labels: enhancement

#1694 Add /usr/local/ibm/gsk8 to TSM_LD_LIBRARY_PATH
  usr/share/rear/conf/default.conf
Labels: bug

#1742 use grub2-install --no-nvram on PowerNV system
  usr/share/rear/finalize/Linux-ppc64le/620_install_grub2.sh
Labels: bug, special hardware

#1744 Add gsk libs to TSM_LD_LIBRARY_PATH
  usr/share/rear/conf/default.conf
  usr/share/rear/prep/TSM/default/400_prep_tsm.sh
Labels: minor bug

#1743 Add dbus user and group by default
  usr/share/rear/conf/GNU/Linux.conf
Labels: enhancement
