Repository rear/rear, pull requests merged in 2018-05, with the labels that each got.

#1792 Better describe NON_FATAL_BINARIES_WITH_MISSING_LIBRARY (issue#1693)
  usr/share/rear/conf/default.conf
Labels: documentation, enhancement

#1794 Solve problem with some variables loading config from DRLM drlm issue brainupdaters/drlm#68
  usr/share/rear/lib/drlm-functions.sh
Labels: bug, cleanup, enhancement

#1791 man page BACKUP SOFTWARE INTEGRATION update (issue#1788)
  doc/rear.8
  doc/rear.8.adoc
Labels: documentation, enhancement, minor bug

#1799 Use Print outside for loop instead of Log (readability)
  usr/share/rear/restore/TSM/default/400_restore_with_tsm.sh
Labels: enhancement

#1801 exclude multipath device that does not have mounted fs
  usr/share/rear/layout/save/default/320_autoexclude.sh
Labels: bug

#1804 Do not start multipathd when not needed
  usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh
Labels: enhancement

#1802 Better way to get multiapth partion name.
  usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
Labels: bug, enhancement, waiting for info

#1813 Make SLES12GA btrfs recovery work again (related to issue 1796)
  usr/share/rear/layout/prepare/GNU/Linux/130_include_mount_subvolumes_code.sh
  usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
Labels: bug

#1806 Issue #1380 - ReaR recovery fails when the OS contains a Thin Pool/Volume
  usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh
  usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh
  usr/share/rear/lib/layout-functions.sh
  usr/share/rear/prep/GNU/Linux/220_include_lvm_tools.sh
Labels: enhancement

#1817 Sesam integration: add sesam bin directory to LD_LIBRARY_PATH
  usr/share/rear/build/default/980_verify_rootfs.sh
  usr/share/rear/lib/sesam-functions.sh
Labels: external tool, minor bug

#1803 Copy backup restore log into recreated system (related to pull request 1797)
  usr/share/rear/conf/default.conf
  usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh
  usr/share/rear/restore/NETFS/default/400_restore_backup.sh
  usr/share/rear/restore/TSM/default/400_restore_with_tsm.sh
  usr/share/rear/wrapup/default/990_copy_logfile.sh
Labels: enhancement
