Repository rear/rear, pull requests merged in 2018-07, with the labels that each got.

#1853 add support for Slackware UEFI/USB
  usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
  usr/share/rear/pack/Linux-i386/300_copy_kernel.sh
Labels: enhancement

#1862 fedora28: missing ldlinux.c32 prevents PXE booting
  usr/share/rear/output/PXE/default/800_copy_to_tftp.sh
Labels: enhancement

#1848 Fixed, simplified and enhanced GRUB2 installation for PPC64/PPC64LE
  usr/share/rear/conf/default.conf
  usr/share/rear/finalize/GNU/Linux/250_migrate_disk_devices_layout.sh
  usr/share/rear/finalize/Linux-i386/620_install_grub2.sh
  usr/share/rear/finalize/Linux-ppc64le/620_install_grub2.sh
  usr/share/rear/lib/layout-functions.sh
Labels: bug, cleanup, documentation, enhancement

#1863 mods to allow slackware ISO image and udev sda fix
  usr/share/rear/lib/uefi-functions.sh
  usr/share/rear/output/ISO/Linux-i386/820_create_iso_image.sh
  usr/share/rear/skel/default/etc/scripts/system-setup.d/40-start-udev-or-load-modules.sh
Labels: enhancement

#1867 fedora28: syslinux needs libcom32.c32 to boot from HD
  usr/share/rear/output/PXE/default/800_copy_to_tftp.sh
Labels: enhancement

#1864 Verify md5sums of files in recovery system (issue #1859)
  usr/share/rear/build/default/995_md5sums_rootfs.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/skel/default/etc/scripts/system-setup
Labels: documentation, enhancement

#1865 Added choice to confirm identical layout mapping only once plus disabling MIGRATION_MODE
  usr/share/rear/layout/prepare/default/300_map_disks.sh
Labels: enhancement, fixed/solved/done

#1872 Aviod duplicate UUID in boot menuentry when snapper is used (issue #1871)
  usr/share/rear/lib/bootloader-functions.sh
Labels: bug

#1869 Wait for systemd-udevd to avoid broken pipe error in 40-start-udev-or-load-modules.sh
  usr/share/rear/skel/default/etc/scripts/system-setup.d/40-start-udev-or-load-modules.sh
Labels: bug, cleanup

#1874 Add code to recognize persistent LAN interface and manipulate KERNEL_CMDLINE
  usr/share/rear/lib/network-functions.sh
  usr/share/rear/rescue/GNU/Linux/290_kernel_cmdline.sh
Labels: enhancement

#1876 Duplicity: Misc improvements
  usr/share/rear/backup/DUPLICITY/default/500_make_duplicity_backup.sh
  usr/share/rear/conf/default.conf
Labels: documentation, enhancement, external tool

#1877 Show last programs messages in Error function (related to issue1875)
  usr/share/rear/lib/_input-output-functions.sh
  usr/share/rear/output/default/200_make_prefix_dir.sh
  usr/share/rear/skel/default/etc/scripts/system-setup
  usr/share/rear/verify/USB/NETFS/default/540_choose_backup_archive.sh
Labels: enhancement

#1882 Yet another Duplicity fix
  usr/share/rear/backup/DUPLICITY/default/500_make_duplicity_backup.sh
Labels: bug, fixed/solved/done
