Repository rear/rear, pull requests merged in 2018-06, with the labels that each got.

#1819 Issue #1722 - Cannot restore disk built on multipath + md
  usr/share/rear/build/GNU/Linux/110_touch_empty_files.sh
  usr/share/rear/build/default/502_include_mdadm_conf.sh
  usr/share/rear/prep/GNU/Linux/230_include_md_tools.sh
Labels: enhancement, minor bug

#1827 Move iproute to Suggests in control file for Debian
  packaging/debian/control
Labels: enhancement, minor bug

#1831 Fixed a typo plus a small addon in comments in default.conf
  usr/share/rear/conf/default.conf
Labels: documentation, enhancement

#1833 Fix BAREOS unattended mode; interrupted with question due to bad IF block
  usr/share/rear/restore/BAREOS/default/400_restore_backup.sh
Labels: enhancement

#1843 Fixed, simplified and enhanced GRUB2 installation
  usr/sbin/rear
  usr/share/rear/conf/default.conf
  usr/share/rear/finalize/GNU/Linux/250_migrate_disk_devices_layout.sh
  usr/share/rear/finalize/GNU/Linux/250_migrate_lun_wwid.sh
  usr/share/rear/finalize/GNU/Linux/260_rename_diskbyid.sh
  usr/share/rear/finalize/GNU/Linux/280_migrate_uuid_tags.sh
  usr/share/rear/finalize/Linux-i386/620_install_grub2.sh
  usr/share/rear/layout/prepare/default/300_map_disks.sh
  usr/share/rear/layout/prepare/default/320_apply_mappings.sh
  usr/share/rear/lib/_input-output-functions.sh
  usr/share/rear/lib/layout-functions.sh
  usr/share/rear/output/ISO/Linux-ia64/800_create_isofs.sh
  usr/share/rear/wrapup/default/990_copy_logfile.sh
Labels: bug, cleanup, documentation, enhancement
