Repository rear/rear, pull requests merged in 2019-11, with the labels that each got.

#2267 Removed verbose option from find.
  usr/share/rear/verify/CDM/default/410_use_replica_cdm_cluster_cert.sh
Labels: bug

#2271 Update 650_check_iso_recoverable.sh
  usr/share/rear/layout/save/NSR/default/650_check_iso_recoverable.sh
Labels: enhancement, minor bug

#2238 Add alternative for 'poweroff.com' ('poweroff.c32' on RHEL8)
  usr/share/rear/lib/bootloader-functions.sh
  usr/share/rear/output/PXE/default/800_copy_to_tftp.sh
  usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh
Labels: enhancement

#2274 Enable copr builds for packit config
  .packit.yaml
Labels: enhancement

#2251 Accommodate logs from multiple FDR/Upstream services. Improve logging.
  usr/share/rear/restore/FDRUPSTREAM/default/260_copy_log_and_report.sh
Labels: enhancement, external tool

#2280 Improved check for missing libraries in 990_verify_rootfs.sh (issue 2279)
  usr/share/rear/build/default/990_verify_rootfs.sh
  usr/share/rear/conf/default.conf
Labels: cleanup, documentation, enhancement

#2278 Feature rawdisk and opalpba improvements
  usr/share/rear/build/OPALPBA/Linux-i386/820_store_settings.sh
  usr/share/rear/conf/Ubuntu.conf
  usr/share/rear/conf/default.conf
  usr/share/rear/output/RAWDISK/Linux-i386/270_create_grub2_efi_bootloader.sh
  usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh
  usr/share/rear/skel/default/etc/scripts/unlock-opal-disks
Labels: bug, enhancement

#2269 Issue 2247: draft implementation of 'mountonly' workflow.
  doc/user-guide/04-scenarios.adoc
  usr/sbin/rear
  usr/share/rear/check/GNU
  usr/share/rear/check/default
  usr/share/rear/final-mount/default/110_bind_mount_proc_sys_dev_run.sh
  usr/share/rear/final-mount/default/900_remount_sync.sh
  usr/share/rear/finalize/default/900_remount_sync.sh
  usr/share/rear/init/default/050_check_rear_recover_mode.sh
  usr/share/rear/layout/do-mount/default/100_confirm_layout_code.sh
  usr/share/rear/layout/do-mount/default/200_run_layout_code.sh
  usr/share/rear/layout/do-mount/default/250_verify_mount.sh
  usr/share/rear/layout/prep-for-mount/GNU/Linux/100_include_partition_code.sh
  usr/share/rear/layout/prep-for-mount/GNU/Linux/110_include_lvm_code.sh
  usr/share/rear/layout/prep-for-mount/GNU/Linux/120_include_raid_code.sh
  usr/share/rear/layout/prep-for-mount/GNU/Linux/131_include_filesystem_code.sh
  usr/share/rear/layout/prep-for-mount/GNU/Linux/133_include_mount_filesystem_code.sh
  usr/share/rear/layout/prep-for-mount/GNU/Linux/135_include_btrfs_subvolumes_generic_code.sh
  usr/share/rear/layout/prep-for-mount/GNU/Linux/136_include_btrfs_subvolumes_SLES_code.sh
  usr/share/rear/layout/prep-for-mount/GNU/Linux/140_include_swap_code.sh
  usr/share/rear/layout/prep-for-mount/GNU/Linux/150_include_drbd_code.sh
  usr/share/rear/layout/prep-for-mount/GNU/Linux/160_include_luks_code.sh
  usr/share/rear/layout/prep-for-mount/GNU/Linux/170_include_hpraid_code.sh
  usr/share/rear/layout/prep-for-mount/GNU/Linux/180_include_opaldisk_code.sh
  usr/share/rear/layout/prep-for-mount/GNU/Linux/210_load_multipath.sh
  usr/share/rear/layout/prep-for-mount/default/010_prepare_files.sh
  usr/share/rear/layout/prep-for-mount/default/250_compare_disks.sh
  usr/share/rear/layout/prep-for-mount/default/270_overrule_migration_mode.sh
  usr/share/rear/layout/prep-for-mount/default/300_map_disks.sh
  usr/share/rear/layout/prep-for-mount/default/310_remove_exclusions.sh
  usr/share/rear/layout/prep-for-mount/default/320_apply_mappings.sh
  usr/share/rear/layout/prep-for-mount/default/500_confirm_layout_file.sh
  usr/share/rear/layout/prep-for-mount/default/510_list_dependencies.sh
  usr/share/rear/layout/prep-for-mount/default/520_exclude_components.sh
  usr/share/rear/layout/prep-for-mount/default/540_generate_device_code.sh
  usr/share/rear/layout/prep-for-mount/default/550_finalize_script.sh
  usr/share/rear/layout/prep-for-mount/default/600_show_unprocessed.sh
  usr/share/rear/layout/prepare/GNU/Linux/160_include_luks_code.sh
  usr/share/rear/layout/prepare/default/250_compare_disks.sh
  usr/share/rear/lib/layout-functions.sh
  usr/share/rear/lib/mountonly-workflow.sh
  usr/share/rear/setup/default/002_clean_start.sh
  usr/share/rear/verify/GNU/Linux/260_recovery_storage_drivers.sh
  usr/share/rear/wrapup/default/980_good_bye.sh
Labels: enhancement

#2286 Do not ckeck untrusted files for missing libraries (issue 2279)
  usr/share/rear/build/GNU/Linux/100_copy_as_is.sh
  usr/share/rear/build/GNU/Linux/390_copy_binaries_libraries.sh
  usr/share/rear/build/GNU/Linux/400_copy_modules.sh
  usr/share/rear/build/GNU/Linux/420_copy_firmware_files.sh
  usr/share/rear/build/default/990_verify_rootfs.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/_input-output-functions.sh
  usr/share/rear/lib/linux-functions.sh
Labels: cleanup, enhancement
