Repository rear/rear, pull requests merged in 2019-03, with the labels that each got.

#2058 Update 470_safe_filesystems.sh for NSR
  usr/share/rear/rescue/NSR/default/470_safe_filesystems.sh
Labels: enhancement

#2064 Udev before multipath
  usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh
Labels: enhancement

#2063 to avoid confusing in mkrescue run we do not print using archive #1363
  usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh
Labels: enhancement

#2060 New verify disklayout file script 950_verify_disklayout_file.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/layout/save/default/950_verify_disklayout_file.sh
  usr/share/rear/lib/global-functions.sh
Labels: enhancement

#2073 Debian packaging: downgrade syslinux from Depends to Suggests
  packaging/debian/control
Labels: enhancement

#2069 Have MODULES all_modules by default plus needed adaptions for that
  usr/share/rear/build/GNU/Linux/400_copy_modules.sh
  usr/share/rear/conf/GNU/Linux.conf
  usr/share/rear/conf/default.conf
Labels: enhancement

#2072 OPALPBA output fix: Do not include any PBA into another PBA
  usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh
Labels: bug, enhancement

#2071 RAWDISK output: improve device partition detection (e.g. Ubuntu 18.04)
  usr/share/rear/output/RAWDISK/Linux-i386/280_create_bootable_disk_image.sh
Labels: bug, enhancement

#2070 Fix SSH root login on the recovery system with some configurations
  usr/share/rear/skel/default/etc/scripts/run-sshd
Labels: bug

#2076 Ignore broken resolv conf in case of use dhclient issue 2018
  usr/share/rear/build/GNU/Linux/630_verify_resolv_conf_file.sh
  usr/share/rear/conf/default.conf
Labels: enhancement, minor bug

#2079 Add new implementation to recreate all mounted Btrfs subvolumes
  usr/share/rear/layout/prepare/GNU/Linux/131_include_new_btrfs_subvolumes_code.sh
Labels: enhancement

#2082 Add 'net-tools' to Debian dependencies as required for 'route' command
  packaging/debian/control
Labels: enhancement

#2084 Fixed comments and messages about '13X_include_...' scripts that had been renamed via issue 2080
  usr/share/rear/layout/prepare/GNU/Linux/131_include_filesystem_code.sh
  usr/share/rear/layout/prepare/GNU/Linux/133_include_mount_filesystem_code.sh
  usr/share/rear/layout/prepare/GNU/Linux/135_include_btrfs_subvolumes_generic_code.sh
  usr/share/rear/layout/prepare/GNU/Linux/136_include_btrfs_subvolumes_SLES_code.sh
Labels: documentation, minor bug

#2083 Update OPALPBA workflow
  usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh
  usr/share/rear/skel/default/etc/scripts/unlock-opal-disks
  usr/share/rear/skel/default/usr/lib/systemd/system/plymouth-start.service
Labels: cleanup, enhancement

#2091 Ignore invalid partitions on eMMC devices of type *rpmb and *boot*
  usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
Labels: enhancement

#2088 Error function must immediately exit (issue #2089)
  usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
  usr/share/rear/lib/_input-output-functions.sh
Labels: critical/security bug

#2092 Call mktemp with sufficent XXXXXXXXXX where needed otherwise use the mktemp default
  usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
  usr/share/rear/skel/default/etc/scripts/dhcp-setup-functions.sh
Labels: cleanup

#2098 Use [*] instead of [@] for array expansion inside a string
  usr/share/rear/finalize/Linux-ppc64le/680_install_PPC_bootlist.sh
Labels: cleanup

#2099 Use simplest way to get current PID in bash 3 (related to issue 2089)
  usr/share/rear/lib/_input-output-functions.sh
Labels: cleanup
