Repository rear/rear, pull requests merged in 2019-10, with the labels that each got.

#2249 Added new BACKUP=CDM method for Rubrik Cloud Data Management (CDM)
  .gitignore
  doc/user-guide/16-Rubrik-CDM.adoc
  usr/share/rear/conf/default.conf
  usr/share/rear/prep/CDM/default/400_prep_cdm.sh
  usr/share/rear/prep/CDM/default/450_check_cdm_client.sh
  usr/share/rear/restore/CDM/default/400_restore_with_cdm.sh
  usr/share/rear/verify/CDM/default/400_verify_cdm.sh
  usr/share/rear/verify/CDM/default/410_use_replica_cdm_cluster_cert.sh
  usr/share/rear/verify/CDM/default/430_gen_rbs_uuid_for_cdm.sh
  usr/share/rear/verify/CDM/default/450_start_cdm_rbs.sh
Labels: enhancement

#2256 Updated link to SuSE documentation
  doc/user-guide/16-Rubrik-CDM.adoc
Labels: documentation

#2235 Improve handling of partition label type for multipath disks
  doc/user-guide/06-layout-configuration.adoc
  usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh
  usr/share/rear/layout/prepare/default/520_exclude_components.sh
  usr/share/rear/layout/save/GNU/Linux/280_multipath_layout.sh
  usr/share/rear/layout/save/default/320_autoexclude.sh
  usr/share/rear/lib/layout-functions.sh
Labels: bug, cleanup, enhancement

#2237 Fix including of multipath disks in backup
  usr/share/rear/lib/layout-functions.sh
Labels: enhancement

#2252 Remove dev null redirection where possible issue1395
  usr/share/rear/backup/RSYNC/GNU/Linux/610_start_selinux.sh
  usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh
  usr/share/rear/backup/RSYNC/default/450_calculate_req_space.sh
  usr/share/rear/backup/RSYNC/default/500_make_rsync_backup.sh
  usr/share/rear/backup/RSYNC/default/700_copy_backup_log.sh
  usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
  usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
  usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
  usr/share/rear/output/RSYNC/default/900_copy_result_files.sh
  usr/share/rear/prep/NETFS/default/400_automatic_exclude_recreate.sh
  usr/share/rear/verify/NBU/default/390_request_point_in_time_restore_parameters.sh
  usr/share/rear/verify/TSM/default/390_request_point_in_time_restore_parameters.sh
  usr/share/rear/verify/default/020_cciss_scsi_engage.sh
Labels: cleanup

#2257 Do not abort in case of invalid user input but retry
  usr/share/rear/conf/default.conf
  usr/share/rear/restore/DP/default/460_press_y_to_continue.sh
  usr/share/rear/verify/GALAXY10/default/550_request_point_in_time_restore_parameters.sh
  usr/share/rear/verify/NBU/default/380_request_client_destination.sh
  usr/share/rear/verify/NBU/default/390_request_point_in_time_restore_parameters.sh
  usr/share/rear/verify/TSM/default/390_request_point_in_time_restore_parameters.sh
  usr/share/rear/verify/default/040_validate_variables.sh
Labels: cleanup, enhancement

#2260 Use is_true() for AUTOEXCLUDE_MULTIPATH and cleanup of get_partition_number()
  usr/share/rear/conf/default.conf
  usr/share/rear/layout/save/default/320_autoexclude.sh
  usr/share/rear/layout/save/default/335_remove_excluded_multipath_vgs.sh
  usr/share/rear/lib/layout-functions.sh
  usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh
  usr/share/rear/prep/YUM/default/070_set_backup_archive.sh
  usr/share/rear/verify/YUM/default/070_set_backup_archive.sh
Labels: cleanup

#2261 Enhanced AUTOEXCLUDE_PATH /media /run /mnt and /tmp
  usr/share/rear/conf/default.conf
Labels: enhancement
