Repository rear/rear, pull requests merged in 2019-08, with the labels that each got.

#2205 Changed double quotes (") to single quotes(') in documentation related to BORG_PASSPHRASE variable.
  doc/user-guide/04-scenarios.adoc
  doc/user-guide/11-multiple-backups.adoc
  usr/share/rear/conf/default.conf
Labels: documentation

#2199 uefi: Search for Grub2 modules in /usr/lib/grub*/x86_64-efi and not in /boot
  usr/share/rear/lib/uefi-functions.sh
Labels: cleanup, enhancement

#2219 Added $BACKUP_OPTIONS to the line with mount_url in 800_copy_to_tftp.…
  usr/share/rear/output/PXE/default/800_copy_to_tftp.sh
  usr/share/rear/output/PXE/default/810_create_pxelinux_cfg.sh
Labels: enhancement

#2195 Handle ppc64el kernel naming
  usr/share/rear/prep/GNU/Linux/400_guess_kernel.sh
Labels: enhancement
