Repository rear/rear, pull requests merged in 2019-05, with the labels that each got.

#2132 NBU: exclude '/usr/openv/netbackup/logs' directory instead of files in directory only
  usr/share/rear/conf/default.conf
Labels: bug

#2119 btrfs subvolumes generic: fix 'subvolume set-default' for older versions
  usr/share/rear/layout/prepare/GNU/Linux/135_include_btrfs_subvolumes_generic_code.sh
Labels: minor bug

#2131 Improve handling of broken symlinks (fix #2129, fix #2130)
  usr/share/rear/build/default/985_fix_broken_links.sh
Labels: bug, enhancement

#2136 reverted rear.spec changes for OBS build failures on SELS11 and RHEl5
  packaging/rpm/rear.spec
Labels: bug

#2145 On-board packit.yaml
  .packit.yaml
Labels: ReaR Project, enhancement

#2147 Improvements and fixes for 950_copy_result_files (related to issue2137)
  usr/share/rear/output/default/950_copy_result_files.sh
Labels: bug

#2117 Fix for issue 2116: added new SUSE-specific script to call 'shim-inst…
  usr/share/rear/finalize/SUSE_LINUX/i386/675_install_shim.sh
Labels: bug, enhancement

#2081 Enable creation of non consecutive partitions
  usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
  usr/share/rear/layout/save/default/950_verify_disklayout_file.sh
  usr/share/rear/lib/layout-functions.sh
Labels: enhancement

#2149 Cleanup OUTPUT=RAMDISK 900_copy_ramdisk.sh (issue2148)
  usr/share/rear/conf/default.conf
  usr/share/rear/conf/templates/RESULT_usage_RAMDISK.txt
  usr/share/rear/output/RAMDISK/Linux-i386/900_copy_ramdisk.sh
  usr/share/rear/output/RAMDISK/default/900_copy_ramdisk.sh
Labels: cleanup

#2150 Enhancements for dasd disks and GRUB2 plus ZIPL bootloader on SLES on s390
  usr/share/rear/finalize/SUSE_LINUX/s390/660_install_grub2_and_zipl.sh
  usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
Labels: enhancement
