Repository rear/rear, pull requests merged in 2019-02, with the labels that each got.

#2034 Multipath optimizations
  usr/share/rear/lib/layout-functions.sh
  usr/share/rear/rescue/GNU/Linux/270_fc_transport_info.sh
Labels: enhancement

#2031 Documentation for EFISTUB boot support.
  doc/user-guide/15-EFISTUB.adoc
Labels: documentation

#2030 Basic support for EFISTUB booting.
  usr/share/rear/conf/default.conf
  usr/share/rear/finalize/Linux-i386/100_EFISTUB_run_efibootmgr.sh
  usr/share/rear/finalize/Linux-i386/630_run_efibootmgr.sh
  usr/share/rear/finalize/default/050_prepare_checks.sh
  usr/share/rear/init/default/010_EFISTUB_check.sh
  usr/share/rear/lib/bootloader-functions.sh
  usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh
  usr/share/rear/output/ISO/Linux-i386/260_EFISTUB_populate.sh
  usr/share/rear/output/ISO/Linux-i386/820_create_iso_image.sh
  usr/share/rear/output/ISO/Linux-i386/830_create_iso_image_EFISTUB.sh
  usr/share/rear/output/default/940_grub2_rescue.sh
  usr/share/rear/output/default/940_grub_rescue.sh
  usr/share/rear/prep/GNU/Linux/500_EFISTUB_check_kernel.sh
  usr/share/rear/prep/ISO/GNU/Linux/360_EFISTUB_prechecks.sh
  usr/share/rear/prep/default/321_EFISTUB_check_uefi_env.sh
  usr/share/rear/rescue/default/850_save_sysfs_uefi_vars.sh
  usr/share/rear/restore/NETFS/Linux-i386/510_selinux_fixfiles_exclude_dirs.sh
Labels: enhancement

#2039 Fix for commit f9e53a33
  usr/share/rear/lib/uefi-functions.sh
Labels: critical/security bug

#2037 Restoring from Borg backup will now do test list of repository
  usr/share/rear/backup/BORG/default/250_mount_usb.sh
  usr/share/rear/backup/BORG/default/900_umount_usb.sh
  usr/share/rear/lib/borg-functions.sh
  usr/share/rear/prep/BORG/default/900_umount_usb.sh
  usr/share/rear/restore/BORG/default/300_load_archives.sh
  usr/share/rear/restore/BORG/default/400_restore_backup.sh
  usr/share/rear/restore/BORG/default/900_umount_usb.sh
  usr/share/rear/verify/BORG/default/100_set_vars.sh
  usr/share/rear/verify/BORG/default/101_check_borg.sh
  usr/share/rear/verify/BORG/default/250_mount_usb.sh
  usr/share/rear/verify/BORG/default/400_check_archive_access.sh
Labels: cleanup, enhancement

#2038 small fix to the 58-start-dhclient.sh script
  usr/share/rear/skel/default/etc/scripts/system-setup.d/58-start-dhclient.sh
Labels: minor bug

#2043 adding clear to PROGS array
  usr/share/rear/conf/GNU/Linux.conf
Labels: enhancement

#2049 add eno-fix.rules to the RULE_FILES array #2046
  usr/share/rear/finalize/GNU/Linux/310_migrate_udev_rules.sh
  usr/share/rear/skel/default/etc/scripts/system-setup.d/55-migrate-network-devices.sh
Labels: enhancement

#2047 Bind mount proc sys dev run at one place issue2045
  usr/share/rear/conf/default.conf
  usr/share/rear/finalize/Debian/i386/550_rebuild_initramfs.sh
  usr/share/rear/finalize/Fedora/i386/550_rebuild_initramfs.sh
  usr/share/rear/finalize/GNU/Linux/280_migrate_uuid_tags.sh
  usr/share/rear/finalize/GNU/Linux/430_create_multipath_config.sh
  usr/share/rear/finalize/Linux-arm/620_restore_arm_bootloader.sh
  usr/share/rear/finalize/Linux-i386/610_EFISTUB_run_efibootmgr.sh
  usr/share/rear/finalize/Linux-i386/630_install_grub.sh
  usr/share/rear/finalize/Linux-i386/640_install_lilo.sh
  usr/share/rear/finalize/Linux-i386/650_install_elilo.sh
  usr/share/rear/finalize/Linux-i386/660_install_grub2.sh
  usr/share/rear/finalize/Linux-i386/670_run_efibootmgr.sh
  usr/share/rear/finalize/Linux-ia64/650_install_elilo.sh
  usr/share/rear/finalize/Linux-ppc64/620_install_grub2.sh
  usr/share/rear/finalize/Linux-ppc64/635_install_yaboot.sh
  usr/share/rear/finalize/Linux-ppc64/640_install_lilo.sh
  usr/share/rear/finalize/Linux-ppc64/660_install_grub2.sh
  usr/share/rear/finalize/Linux-ppc64le/660_install_grub2.sh
  usr/share/rear/finalize/SUSE_LINUX/i386/550_rebuild_initramfs.sh
  usr/share/rear/finalize/default/100_populate_dev.sh
  usr/share/rear/finalize/default/110_bind_mount_proc_sys_dev_run.sh
  usr/share/rear/finalize/default/890_finish_checks.sh
  usr/share/rear/restore/NETFS/Linux-i386/510_selinux_fixfiles_exclude_dirs.sh
  usr/share/rear/restore/YUM/default/950_grub2_mkconfig.sh
  usr/share/rear/restore/ZYPPER/default/950_grub2_mkconfig.sh
Labels: bug, cleanup, enhancement

#2055 skip patching absolute symlinks during finalize stage (related to issue 1338)
  usr/share/rear/finalize/GNU/Linux/250_migrate_disk_devices_layout.sh
  usr/share/rear/finalize/GNU/Linux/250_migrate_lun_wwid.sh
  usr/share/rear/finalize/GNU/Linux/260_rename_diskbyid.sh
  usr/share/rear/finalize/GNU/Linux/280_migrate_uuid_tags.sh
  usr/share/rear/finalize/GNU/Linux/310_migrate_udev_rules.sh
  usr/share/rear/finalize/GNU/Linux/320_migrate_network_configuration_files.sh
  usr/share/rear/finalize/default/520_confirm_finalize.sh
Labels: bug, cleanup, enhancement
