Repository rear/rear, pull requests merged in 2019-09, with the labels that each got.

#2201 Fix for issue 2200: support new use-case for BLOCKCLONE backup method…
  doc/user-guide/11-multiple-backups.adoc
  doc/user-guide/12-BLOCKCLONE.adoc
  usr/share/rear/backup/BLOCKCLONE/default/500_start_clone.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/global-functions.sh
  usr/share/rear/restore/BLOCKCLONE/default/400_restore_clone.sh
Labels: enhancement

#2226 Fix typo
  doc/user-guide/03-configuration.adoc
Labels: cleanup

#2225 Use mountpoint instead of mount|grep
  usr/share/rear/lib/framework-functions.sh
  usr/share/rear/verify/DUPLICITY/default/200_check_tmpfs.sh
Labels: cleanup, enhancement

#2233 remove obsolete Fedora 16/17 skel systemd stuff
  usr/share/rear/skel/Fedora/16/lib/systemd/system/udev-settle.service
  usr/share/rear/skel/Fedora/16/lib/systemd/system/udev-trigger.service
  usr/share/rear/skel/Fedora/16/lib/systemd/system/udev.service
  usr/share/rear/skel/Fedora/17/usr/lib/systemd/system/udev-settle.service
  usr/share/rear/skel/Fedora/17/usr/lib/systemd/system/udev-trigger.service
  usr/share/rear/skel/Fedora/17/usr/lib/systemd/system/udev.service
Labels: cleanup

#2218 Do not keep the build dir when used noninteractively
  usr/share/rear/build/default/990_verify_rootfs.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/framework-functions.sh
Labels: cleanup, discuss / RFC
