Repository rear/rear, pull requests merged in 2019-12, with the labels that each got.

#2283 Currently, ReaR is using hard-coded set of Grub2 modules for UEFI
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/uefi-functions.sh
  usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh
  usr/share/rear/output/default/940_grub2_rescue.sh
Labels: cleanup, enhancement

#2292 Updated links to Borg documentation.
  doc/user-guide/04-scenarios.adoc
Labels: documentation

#2297 Revert part of #1961 : move route back from REQUIRED_PROGS to PROGS
  usr/share/rear/conf/GNU/Linux.conf
Labels: cleanup

#2295 Issue 2281(missing delete_dummy_partitions_and_resize_real_ones calls)
  usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
  usr/share/rear/layout/prepare/GNU/Linux/120_include_raid_code.sh
  usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh
Labels: bug, cleanup

#2291 Error out in case of insufficient LVM tools (issue 2259)
  doc/user-guide/06-layout-configuration.adoc
  usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh
  usr/share/rear/layout/save/default/950_verify_disklayout_file.sh
Labels: bug, cleanup, enhancement

#2299 Better is_multipath_path function (issue #2298) plus some other stuff
  usr/share/rear/conf/GNU/Linux.conf
  usr/share/rear/layout/prepare/default/010_prepare_files.sh
  usr/share/rear/layout/save/GNU/Linux/100_create_layout_file.sh
  usr/share/rear/lib/layout-functions.sh
Labels: bug, cleanup, enhancement

#2142 support for s390 (zLinux) arch
  etc/rear/local.conf
  usr/share/rear/build/default/975_update_os_conf.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/finalize/Fedora/s390/660_install_zipl.sh
  usr/share/rear/layout/prepare/GNU/Linux/100_include_partition_code.sh
  usr/share/rear/layout/prepare/GNU/Linux/133_include_mount_filesystem_code.sh
  usr/share/rear/layout/prepare/Linux-s390/205_s390_enable_disk.sh
  usr/share/rear/layout/save/FDRUPSTREAM/Linux-s390/990_copy_disklayout_file.sh
  usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
  usr/share/rear/layout/save/default/445_guess_bootloader.sh
  usr/share/rear/layout/save/default/450_check_bootloader_files.sh
  usr/share/rear/layout/save/default/950_verify_disklayout_file.sh
  usr/share/rear/output/IPL/Linux-s390/800_create_ipl.sh
  usr/share/rear/output/default/950_copy_result_files.sh
  usr/share/rear/pack/GNU/Linux/900_create_initramfs.sh
  usr/share/rear/prep/GNU/Linux/300_include_grub_tools.sh
  usr/share/rear/prep/GNU/Linux/400_guess_kernel.sh
  usr/share/rear/prep/Linux-s390/305_include_s390_tools.sh
  usr/share/rear/rescue/GNU/Linux/230_storage_and_network_modules.sh
  usr/share/rear/rescue/GNU/Linux/310_network_devices.sh
Labels: enhancement

#2302 Remove outdated /root/rear-DATE-TIMESTAMP.log symlinks (issue#2301)
  usr/share/rear/wrapup/default/990_copy_logfile.sh
Labels: cleanup, minor bug

#2303 Enhanced recovery system BIOS boot default settings for USB and ISO (related to issue 2276
  usr/share/rear/conf/default.conf
  usr/share/rear/conf/templates/rear.help
  usr/share/rear/lib/bootloader-functions.sh
  usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh
Labels: documentation, enhancement
