Repository rear/rear, pull requests merged in 2020-11, with the labels that each got.

#2488 Support OPAL 2 self-encrypting NVMe disk drives (fix #2475)
  usr/share/rear/lib/layout-functions.sh
  usr/share/rear/lib/opal-functions.sh
  usr/share/rear/skel/default/etc/scripts/unlock-opal-disks
Labels: enhancement

#2507 Fix #2474: add AMD firmware to OPAL PBA if necessary
  usr/share/rear/conf/GNU/Linux.conf
  usr/share/rear/conf/default.conf
  usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh
Labels: enhancement

#2506 Make recreating LUKS volumes work with optional cryptsetup options
  usr/share/rear/layout/prepare/GNU/Linux/160_include_luks_code.sh
  usr/share/rear/layout/save/GNU/Linux/260_crypt_layout.sh
Labels: cleanup, enhancement

#2512 Improve TCG Opal 2 Documentation, fix #2511
  doc/user-guide/13-tcg-opal-support.adoc
Labels: documentation, enhancement

#2515 Restore the LD_LIBRARY_PATH after reporting binaries with 'not found' shared objects
  usr/share/rear/build/default/990_verify_rootfs.sh
Labels: minor bug

#2520 Better wording in user messages about keyboard issues
  usr/share/rear/rescue/GNU/Linux/500_clone_keyboard_mappings.sh
Labels: enhancement

#2523 Completely overhauled ldd test in 990_verify_rootfs.sh
  usr/share/rear/build/default/990_verify_rootfs.sh
Labels: cleanup, enhancement, minor bug

#2525 Error out when files greater or equal ISO_FILE_SIZE_LIMIT should be included in the ISO
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/output-functions.sh
  usr/share/rear/output/ISO/Linux-i386/810_prepare_multiple_iso.sh
  usr/share/rear/output/ISO/Linux-i386/820_create_iso_image.sh
  usr/share/rear/output/ISO/Linux-i386/830_create_iso_image_EFISTUB.sh
  usr/share/rear/output/ISO/Linux-ia64/800_create_isofs.sh
  usr/share/rear/output/ISO/Linux-ppc64le/820_create_iso_image.sh
  usr/share/rear/prep/ISO/GNU/Linux/320_verify_mkisofs.sh
Labels: critical/security bug, enhancement
