Repository rear/rear, pull requests merged in 2020-06, with the labels that each got.

#2420 Fix #2419: RAWDISK output fails to boot with Grub 2 on UEFI
  usr/share/rear/output/RAWDISK/Linux-i386/270_create_grub2_efi_bootloader.sh
Labels: bug, enhancement

#2422 Also parse SSH Include files in 501_check_ssh_keys.sh
  usr/share/rear/build/default/501_check_ssh_keys.sh
Labels: cleanup, enhancement

#2426 Fix #2425: OPALPBA: Reboot after SED-unlocking may hang on UEFI systems
  usr/share/rear/prep/default/380_include_opal_tools.sh
  usr/share/rear/skel/default/etc/scripts/unlock-opal-disks
Labels: enhancement

#2427 Add DHCP auto-configuration for Network Manager (Ubuntu 20.04 Desktop)
  usr/share/rear/prep/GNU/Linux/210_include_dhclient.sh
Labels: enhancement

#2431 Migrate XFS configuration files.
  usr/share/rear/layout/prepare/GNU/Linux/131_include_filesystem_code.sh
  usr/share/rear/layout/prepare/default/010_prepare_files.sh
  usr/share/rear/layout/prepare/default/319_rename_xfs_configs.sh
  usr/share/rear/layout/save/GNU/Linux/100_create_layout_file.sh
Labels: bug, enhancement

#2437 Add "--type luks1" to the default LUKS_CRYPTSETUP_OPTIONS
  usr/share/rear/conf/default.conf
Labels: enhancement, minor bug
