Repository rear/rear, pull requests merged in 2020-05, with the labels that each got.

#2390 No longer load video_bochs and video_cirrus by the create_grub2_cfg function
  usr/share/rear/lib/bootloader-functions.sh
Labels: bug

#2382 Improve borg integration into rear
  usr/share/rear/backup/BORG/default/100_get_suffix.sh
  usr/share/rear/backup/BORG/default/500_make_backup.sh
  usr/share/rear/backup/BORG/default/800_prune_old_backups.sh
  usr/share/rear/backup/BORG/default/900_umount_usb.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/borg-functions.sh
  usr/share/rear/prep/BORG/default/100_set_vars.sh
  usr/share/rear/prep/BORG/default/200_prep_borg.sh
  usr/share/rear/prep/BORG/default/250_mount_usb.sh
  usr/share/rear/prep/BORG/default/300_init_archive.sh
  usr/share/rear/restore/BORG/default/300_load_archives.sh
  usr/share/rear/restore/BORG/default/400_restore_backup.sh
  usr/share/rear/verify/BORG/default/400_check_archive_access.sh
Labels: enhancement

#2395 Error out for unsupported workflow in any case
  usr/share/rear/init/default/050_check_rear_recover_mode.sh
Labels: blocker, critical/security bug

#2393 Make GRUB2_MODULES variables having UEFI specific names (issue 2392)
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/uefi-functions.sh
Labels: blocker, cleanup

#2396 Safeguard prep/USB/<non-i386-arch>/350_safeguard_error_out.sh scripts (issue 2348)
  usr/share/rear/conf/default.conf
  usr/share/rear/prep/USB/Linux-arm/350_safeguard_error_out.sh
  usr/share/rear/prep/USB/Linux-ppc64/350_safeguard_error_out.sh
  usr/share/rear/prep/USB/Linux-ppc64le/350_safeguard_error_out.sh
  usr/share/rear/prep/USB/Linux-s390/350_safeguard_error_out.sh
Labels: documentation, enhancement

#2397 Update 950_check_missing_programs.sh
  usr/share/rear/init/default/950_check_missing_programs.sh
Labels: bug

#2384 New OUTPUT_LFTP_OPTIONS config variable for lftp custom parameters
  usr/share/rear/conf/default.conf
  usr/share/rear/output/PXE/default/820_copy_to_net.sh
  usr/share/rear/output/default/950_copy_result_files.sh
Labels: enhancement

#2399 CLONE_ALL_USERS_GROUPS="true" by default
  usr/share/rear/conf/default.conf
Labels: cleanup, documentation, enhancement

#2401 Create destination directory schema when using lftp
  usr/share/rear/output/PXE/default/820_copy_to_net.sh
  usr/share/rear/output/default/950_copy_result_files.sh
Labels: enhancement

#2402 Updated generated locale filename from "rear.UTF-8" to "en_US.UTF-8" (BACKUP=BORG)
  usr/share/rear/lib/borg-functions.sh
  usr/share/rear/prep/BORG/default/200_prep_borg.sh
Labels: cleanup, minor bug

#2409 Add proper comments of reason of these 2 scripts around SELinux #1957
  usr/share/rear/restore/NETFS/default/500_selinux_autorelabel.sh
  usr/share/rear/restore/default/500_selinux_autorelabel.sh
Labels: documentation

#2408 Work on selecting the Borg archive to restore from.
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/borg-functions.sh
  usr/share/rear/restore/BORG/default/300_load_archives.sh
Labels: cleanup, enhancement

#2410 Evaluate OUTPUT_LFTP_OPTIONS at the beginning of lftp operations.
  usr/share/rear/output/PXE/default/820_copy_to_net.sh
  usr/share/rear/output/default/950_copy_result_files.sh
Labels: enhancement, minor bug

#2411 Adjust some doc files to use new `BORGBACKUP_PRUNE_KEEP_*` variables.
  doc/user-guide/04-scenarios.adoc
  doc/user-guide/11-multiple-backups.adoc
  usr/share/rear/conf/examples/borg-example.conf
Labels: documentation, minor bug
