Repository rear/rear, pull requests merged in 2020-08, with the labels that each got.

#2470 500_make_backup.sh: fix exit code logic
  usr/share/rear/backup/NETFS/default/500_make_backup.sh
Labels: bug

#2466 500_make_backup.sh: filter informational tar messages from output
  usr/share/rear/backup/NETFS/default/500_make_backup.sh
Labels: enhancement

#2469 In 400_copy_modules.sh skip copying kernel modules that are builtin modules (issue 2414)
  usr/share/rear/build/GNU/Linux/400_copy_modules.sh
Labels: enhancement

#2478 Have 'cd WORKING_DIR' in Source() function
  usr/sbin/rear
  usr/share/rear/lib/framework-functions.sh
Labels: cleanup

#2485 Adding arch:ppc64le
  .travis.yml
Labels: enhancement
