Repository rear/rear, pull requests merged in 2020-03, with the labels that each got.

#2313 Cleanup and enhance 320_migrate_network_configuration_files.sh (issue 2310)
  usr/share/rear/finalize/GNU/Linux/320_migrate_network_configuration_files.sh
Labels: bug, cleanup, enhancement, needs sponsorship, waiting for info

#2326 Allow to boot original system from Grub menu (UEFI)
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/bootloader-functions.sh
  usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
  usr/share/rear/output/default/940_grub2_rescue.sh
  usr/share/rear/rescue/default/860_set_uefi_vars.sh
Labels: cleanup, enhancement

#2342 Add missing but required NFS users for proper rpcbind startup
  usr/share/rear/prep/NETFS/default/100_check_nfs_version.sh
Labels: enhancement, minor bug

#2346 Have '-iso-level 3' option also for ppc64le
  usr/share/rear/output/ISO/Linux-ppc64le/820_create_iso_image.sh
Labels: enhancement

#2347 Overhauled ISO_MAX_SIZE implementation in 500_make_backup.sh
  usr/share/rear/backup/NETFS/default/500_make_backup.sh
Labels: cleanup, enhancement, minor bug

#2350 Fix #2349: OPALPBA: cannot change password on multiple SEDs at once
  usr/share/rear/lib/opaladmin-workflow.sh
Labels: minor bug

#2353 Fix #2351, #2352: relax checking for a valid BACKUP method
  usr/share/rear/restore/OPALPBA/readme
Labels: bug, cleanup, enhancement
