Repository rear/rear, pull requests merged in 2020-09, with the labels that each got.

#2489 Makefile: fix warning "jobserver unavailable: using -j1"
  Makefile
Labels: minor bug

#2493 Inform the user about unsupported LUKS2 volumes but do not error out
  usr/share/rear/layout/save/GNU/Linux/260_crypt_layout.sh
Labels: bug, enhancement

#2495 More verbose messages when components are excluded
  usr/share/rear/layout/save/default/310_include_exclude.sh
  usr/share/rear/layout/save/default/320_autoexclude.sh
  usr/share/rear/layout/save/default/330_remove_exclusions.sh
  usr/share/rear/layout/save/default/335_remove_excluded_multipath_vgs.sh
  usr/share/rear/layout/save/default/950_verify_disklayout_file.sh
  usr/share/rear/lib/layout-functions.sh
  usr/share/rear/prep/NETFS/default/400_automatic_exclude_recreate.sh
Labels: enhancement
