Repository rear/rear, pull requests merged in 2020-04, with the labels that each got.

#2361 Fix 2360: Apply xxx_fix_broken_links.sh before files get modified in recovery system
  usr/share/rear/build/default/490_fix_broken_links.sh
Labels: bug, enhancement

#2363 Fix/sshd config
  usr/share/rear/build/default/500_ssh_setup.sh
  usr/share/rear/skel/default/etc/scripts/run-sshd
Labels: bug, enhancement

#2373 Skip Longhorn Engine replica devices
  usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
Labels: minor bug

#2381 Error out when LUKS version 2 is used (issue #2204)
  usr/share/rear/layout/save/GNU/Linux/260_crypt_layout.sh
Labels: minor bug

#2378 Filter out duplicates in COPY_AS_IS and copy_as_is_filelist_file
  usr/share/rear/build/GNU/Linux/100_copy_as_is.sh
Labels: cleanup, discuss / RFC, enhancement

#2370 Use "dd ... bs=1M" in backup/NETFS/default/500_make_backup.sh
  usr/share/rear/backup/NETFS/default/500_make_backup.sh
Labels: enhancement
