Repository rear/rear, pull requests merged in 2020-12, with the labels that each got.

#2529 NBKDC: Fix ReaR backup and restore with NovaStor DataCenter 8.0 and higher
  doc/rear-release-notes.txt
  doc/rear.8
  doc/rear.8.adoc
  usr/share/rear/conf/default.conf
  usr/share/rear/prep/NBKDC/default/400_prep_nbkdc.sh
  usr/share/rear/restore/NBKDC/default/400_restore_backup.sh
Labels: enhancement, external tool

#2532 ppc64 support for BACKUP=DP
  usr/share/rear/prep/DP/default/450_check_dp_client_configured.sh
  usr/share/rear/restore/DP/default/450_restore_via_gui.sh
  usr/share/rear/verify/DP/default/400_verify_dp.sh
  usr/share/rear/verify/DP/default/450_request_gui_restore.sh
Labels: enhancement, external tool

#2533 ISO_FILE_SIZE_LIMIT: provide final power to the user to skip the ISO_FILE_SIZE_LIMIT test
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/output-functions.sh
  usr/share/rear/prep/ISO/GNU/Linux/320_verify_mkisofs.sh
Labels: enhancement

#2537 Completely overhauled USB filesystem kernel module handling
  usr/sbin/rear
  usr/share/rear/prep/USB/default/380_copy_usb_fs_module.sh
  usr/share/rear/skel/default/etc/scripts/system-setup.d/40-start-udev-or-load-modules.sh
Labels: cleanup, enhancement, minor bug

#2550 Correct travis parse error. Add additional steps
  .travis.yml
Labels: enhancement
