Repository rear/rear, pull requests merged in 2021-05, with the labels that each got.

#2603 #2596 Have unused LVM PV devices only as comment in disklayout.conf file
  usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh
Labels: enhancement

#2608 Fix setting boot path in case of UEFI partition (ESP) on MD RAID
  usr/share/rear/finalize/Linux-i386/670_run_efibootmgr.sh
  usr/share/rear/lib/layout-functions.sh
Labels: bug, cleanup, enhancement

#2609 Better description and error checking for GRUB_RESCUE with UEFI plus some alignment with create_grub2_cfg function
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/uefi-functions.sh
  usr/share/rear/output/default/940_grub2_rescue.sh
Labels: documentation, enhancement

#2613 In 400_save_directories.sh also exclude mountpoints below mountpoints of "type autofs"
  usr/share/rear/prep/default/400_save_directories.sh
Labels: enhancement

#2620 Add BACKUP_DUPLICITY_OPTIONS to restore script
  usr/share/rear/restore/DUPLICITY/default/400_restore_duplicity.sh
Labels: enhancement, minor bug
