Repository rear/rear, pull requests merged in 2021-01, with the labels that each got.

#2549 Add DP_LD_LIBRARY_PATH to include shared libraries used by BACKUP=DP
  usr/share/rear/build/default/990_verify_rootfs.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/finalize/DP/default/500_restore_ssc.sh
Labels: enhancement, external tool

#2546 fixed vfat mkfs using uuid from layout if possible
  usr/share/rear/layout/prepare/GNU/Linux/131_include_filesystem_code.sh
Labels: minor bug

#2535 #2152: make bacula aware of different location of config files
  usr/share/rear/conf/default.conf
  usr/share/rear/prep/BACULA/default/400_prep_bacula.sh
  usr/share/rear/prep/BACULA/default/450_check_BACULA_client_configured.sh
  usr/share/rear/prep/BACULA/default/500_check_BACULA_bconsole_results.sh
  usr/share/rear/prep/OBDR/BACULA/default/030_bextract_tape_device.sh
  usr/share/rear/verify/BACULA/default/050_check_requirements.sh
  usr/share/rear/verify/BACULA/default/100_start_bacula-fd.sh
Labels: enhancement, external tool, minor bug, waiting for info

#2538 RAWDISK: Add local rescue partition installation capability
  usr/share/rear/conf/default.conf
  usr/share/rear/output/RAWDISK/Linux-i386/280_create_bootable_disk_image.sh
  usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh
Labels: enhancement

#2544 Changes for NetBackup (NBU) support
  usr/share/rear/conf/default.conf
  usr/share/rear/rescue/NBU/default/450_prepare_netbackup.sh
  usr/share/rear/skel/NBU/usr/openv/tmp/.gitignore
Labels: enhancement, external tool

#2539 Add terminal password check via 'TTY_ROOT_PASSWORD'
  usr/share/rear/build/default/503_store_tty_root_password.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/prep/default/340_include_password_tools.sh
  usr/share/rear/skel/default/bin/login
Labels: enhancement
