Repository rear/rear, pull requests merged in 2021-12, with the labels that each got.

#2721 Improved wiping disks
  usr/share/rear/conf/default.conf
  usr/share/rear/layout/recreate/default/120_confirm_wipedisk_disks.sh
  usr/share/rear/layout/recreate/default/150_wipe_disks.sh
Labels: enhancement, minor bug

#2723 fixed pxe file cp and permissions for sshfs target
  usr/share/rear/output/PXE/default/800_copy_to_tftp.sh
Labels: bug

#2726 Automatically resize active last partitions on RAID1 disks
  usr/share/rear/layout/prepare/default/250_compare_disks.sh
  usr/share/rear/layout/prepare/default/300_map_disks.sh
  usr/share/rear/layout/prepare/default/420_autoresize_last_partitions.sh
Labels: enhancement

#2731 Fix function modinfo_filename in 400_copy_modules.sh
  usr/share/rear/build/GNU/Linux/400_copy_modules.sh
Labels: bug

#2729 also add ssh-add prog when ssh-agent is added
  usr/share/rear/rescue/default/500_ssh.sh
Labels: enhancement
