Repository rear/rear, pull requests merged in 2021-06, with the labels that each got.

#2625 Fix backup removal in exit task and cleanup handling of URL mountpoints
  usr/share/rear/backup/DUPLICITY/default/100_mount_duplicity_path.sh
  usr/share/rear/backup/DUPLICITY/default/980_unmount_duplicity_path.sh
  usr/share/rear/backup/NETFS/default/100_mount_NETFS_path.sh
  usr/share/rear/backup/NETFS/default/150_save_copy_of_prefix_dir.sh
  usr/share/rear/backup/NETFS/default/200_make_prefix_dir.sh
  usr/share/rear/backup/NETFS/default/250_create_lock.sh
  usr/share/rear/backup/NETFS/default/970_remove_lock.sh
  usr/share/rear/backup/NETFS/default/980_umount_NETFS_dir.sh
  usr/share/rear/backup/YUM/default/400_create_include_exclude_files.sh
  usr/share/rear/build/YUM/default/600_create_python_symlink.sh
  usr/share/rear/finalize/Linux-i386/670_run_efibootmgr.sh
  usr/share/rear/lib/framework-functions.sh
  usr/share/rear/lib/global-functions.sh
  usr/share/rear/output/PXE/default/800_copy_to_tftp.sh
  usr/share/rear/output/PXE/default/810_create_pxelinux_cfg.sh
  usr/share/rear/output/PXE/default/820_copy_to_net.sh
  usr/share/rear/output/default/100_mount_output_path.sh
  usr/share/rear/output/default/150_save_copy_of_prefix_dir.sh
  usr/share/rear/output/default/200_make_prefix_dir.sh
  usr/share/rear/output/default/250_create_lock.sh
  usr/share/rear/output/default/950_copy_result_files.sh
  usr/share/rear/output/default/970_remove_lock.sh
  usr/share/rear/output/default/980_umount_output_dir.sh
  usr/share/rear/prep/BORG/default/250_mount_usb.sh
  usr/share/rear/prep/YUM/default/070_set_backup_archive.sh
  usr/share/rear/restore/DUPLICITY/default/100_mount_duplicity_path.sh
  usr/share/rear/restore/DUPLICITY/default/980_unmount_duplicity_path.sh
  usr/share/rear/restore/YUM/default/100_mount_YUM_path.sh
  usr/share/rear/restore/YUM/default/980_umount_YUM_dir.sh
  usr/share/rear/verify/DUPLICITY/default/100_mount_duplicity_path.sh
  usr/share/rear/verify/DUPLICITY/default/980_unmount_duplicity_path.sh
  usr/share/rear/verify/YUM/default/050_check_YUM_requirements.sh
  usr/share/rear/verify/YUM/default/060_mount_YUM_path.sh
  usr/share/rear/verify/YUM/default/070_set_backup_archive.sh
  usr/share/rear/verify/YUM/default/980_umount_YUM_dir.sh
Labels: cleanup, critical/security bug

#2633 Have stdout and stderr also in non-debug modes
  usr/sbin/rear
  usr/share/rear/lib/_input-output-functions.sh
  usr/share/rear/lib/framework-functions.sh
Labels: cleanup, enhancement

#2632 Cleanup rsync and fix error reporting
  usr/share/rear/backup/NETFS/default/500_make_backup.sh
  usr/share/rear/backup/RSYNC/GNU/Linux/610_start_selinux.sh
  usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh
  usr/share/rear/backup/RSYNC/default/200_check_rsync_relative_option.sh
  usr/share/rear/backup/RSYNC/default/500_make_rsync_backup.sh
  usr/share/rear/backup/RSYNC/default/700_copy_backup_log.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/output/RSYNC/default/200_make_prefix_dir.sh
  usr/share/rear/output/RSYNC/default/900_copy_result_files.sh
  usr/share/rear/prep/NETFS/default/400_automatic_exclude_recreate.sh
  usr/share/rear/prep/RSYNC/GNU/Linux/200_selinux_in_use.sh
  usr/share/rear/prep/RSYNC/default/100_check_rsync.sh
  usr/share/rear/prep/RSYNC/default/150_check_rsync_protocol_version.sh
  usr/share/rear/restore/DUPLICITY/default/400_restore_duplicity.sh
  usr/share/rear/restore/RBME/default/400_restore_backup.sh
  usr/share/rear/restore/RSYNC/default/200_remove_relative_rsync_option.sh
  usr/share/rear/restore/RSYNC/default/400_restore_rsync_backup.sh
  usr/share/rear/verify/RSYNC/GNU/Linux/600_check_rsync_xattr.sh
  usr/share/rear/verify/RSYNC/default/550_check_remote_backup_archive.sh
Labels: bug, cleanup

#2636 Workaround against DRBD9 restore issue #2634
  usr/share/rear/layout/prepare/GNU/Linux/150_include_drbd_code.sh
Labels: discuss / RFC, enhancement
