Repository rear/rear, pull requests merged in 2021-07, with the labels that each got.

#2641 NSR - Enhancement with a new parameter and the ability of a point-in-time recovery.
  usr/share/rear/conf/default.conf
  usr/share/rear/restore/NSR/default/400_restore_with_nsr.sh
  usr/share/rear/verify/NSR/default/390_request_point_in_time_restore_parameters.sh
Labels: enhancement

#2643 Avoid false Error() exit in copy_binaries() in 390_copy_binaries_libraries.sh
  usr/share/rear/build/GNU/Linux/390_copy_binaries_libraries.sh
Labels: minor bug

#2618 Treat RAID layout value '-unknown-' same as an empty value
  usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh
Labels: bug

#2658 Better default USER_INPUT_MAX_CHARS=0 makes correcting the input possible
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/_input-output-functions.sh
Labels: fixed / solved / done, minor bug

#2655 added grub bootloader for USB
  usr/share/rear/conf/default.conf
  usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
  usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh
  usr/share/rear/output/USB/Linux-i386/300_create_grub.sh
  usr/share/rear/output/USB/Linux-i386/830_copy_kernel_initrd.sh
  usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh
Labels: enhancement

#2656 fixed output usb format script for none efi cases
  usr/share/rear/format/USB/default/300_format_usb_disk.sh
Labels: bug

#2660 Cleanup USB format scripts
  usr/share/rear/format/USB/default/200_check_usb_layout.sh
  usr/share/rear/format/USB/default/300_format_usb_disk.sh
  usr/share/rear/format/USB/default/350_label_usb_disk.sh
  usr/share/rear/lib/format-workflow.sh
  usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh
Labels: cleanup, enhancement

#2659 Simplifications for USB_BOOTLOADER="grub"
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/bootloader-functions.sh
  usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
  usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh
  usr/share/rear/output/USB/Linux-i386/300_create_grub.sh
  usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh
Labels: cleanup, enhancement

#2661 Fix grub config
  usr/share/rear/lib/bootloader-functions.sh
Labels: enhancement

#2650 fixed serial console for syslinux
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/bootloader-functions.sh
  usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh
Labels: bug
