Repository rear/rear, pull requests merged in 2021-11, with the labels that each got.

#2705 minimal changes needed for hybrid boot (bios+uefi)
  usr/share/rear/format/USB/default/300_format_usb_disk.sh
  usr/share/rear/format/USB/default/350_label_usb_disk.sh
  usr/share/rear/lib/format-workflow.sh
  usr/share/rear/rescue/default/850_save_sysfs_uefi_vars.sh
Labels: enhancement, cleanup, hacktoberfest-accepted

#2703 Enhanced disk write-protection
  usr/share/rear/conf/default.conf
  usr/share/rear/layout/prepare/default/300_map_disks.sh
  usr/share/rear/lib/write-protect-functions.sh
  usr/share/rear/prep/RAWDISK/Linux-i386/480_initialize_write_protect_settings.sh
  usr/share/rear/prep/USB/default/480_initialize_write_protect_settings.sh
  usr/share/rear/prep/default/490_store_write_protect_settings.sh
Labels: enhancement

#2708 New function is_multipath_used in layout-functions.sh
  usr/share/rear/lib/layout-functions.sh
Labels: enhancement, blocker

#2714 Overhauled RAID code
  doc/user-guide/06-layout-configuration.adoc
  usr/share/rear/conf/default.conf
  usr/share/rear/layout/prepare/GNU/Linux/120_include_raid_code.sh
  usr/share/rear/layout/recreate/default/120_confirm_wipedisk_disks.sh
  usr/share/rear/layout/recreate/default/150_wipe_disks.sh
  usr/share/rear/layout/recreate/default/220_verify_layout.sh
  usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh
Labels: enhancement, cleanup
