Repository rear/rear, pull requests merged in 2022-09, with the labels that each got.

#2846 implement BORGBACKUP_IGNORE_WARNING
  usr/share/rear/backup/BORG/default/500_make_backup.sh
  usr/share/rear/conf/default.conf
Labels: enhancement

#2859 By default let "rear recover" wipe disks that get completely recreated
  usr/share/rear/conf/default.conf
Labels: enhancement

#2857 Insert '$pxe_link_prefix' also "if has_binary gethostip" in the IP case
  usr/share/rear/output/PXE/default/810_create_pxelinux_cfg.sh
Labels: minor bug

#2855 GitHub Workflows security hardening
  .github/workflows/stale.yml
Labels: enhancement, ReaR Project

#2868 In the UserInput function drain stdin if stdin is a terminal
  usr/share/rear/lib/_input-output-functions.sh
Labels: enhancement, minor bug

#2872 Improved comments in default.conf
  usr/share/rear/conf/default.conf
Labels: enhancement

#2842 Modernize Packit configuration
  .packit.yaml
Labels: enhancement
