Repository rear/rear, pull requests merged in 2022-07, with the labels that each got.

#2829 Set USB_DEVICE_PARTED_LABEL to match format-workflow.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/format/USB/default/300_format_usb_disk.sh
  usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
  usr/share/rear/prep/USB/Linux-i386/340_find_mbr_bin.sh
Labels: enhancement, cleanup, minor bug, blocker

#2834 Add yes to REQUIRED_PROGS
  usr/share/rear/conf/GNU/Linux.conf
Labels: blocker

#2830 Support creation of EFI system partition on systems with older `parted`
  usr/share/rear/format/USB/default/300_format_usb_disk.sh
Labels: enhancement, blocker

#2831 Refactor rsync URL support, fixes rsync OUTPUT_URL
  usr/share/rear/backup/NETFS/default/200_check_rsync_relative_option.sh
  usr/share/rear/backup/NETFS/default/210_check_rsync_relative_option.sh
  usr/share/rear/backup/RSYNC/GNU/Linux/610_start_selinux.sh
  usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh
  usr/share/rear/backup/RSYNC/default/200_make_prefix_dir.sh
  usr/share/rear/backup/RSYNC/default/210_check_rsync_relative_option.sh
  usr/share/rear/backup/RSYNC/default/450_calculate_req_space.sh
  usr/share/rear/backup/RSYNC/default/500_make_rsync_backup.sh
  usr/share/rear/backup/RSYNC/default/700_copy_backup_log.sh
  usr/share/rear/lib/global-functions.sh
  usr/share/rear/lib/rsync-functions.sh
  usr/share/rear/output/RSYNC/default/200_make_prefix_dir.sh
  usr/share/rear/output/RSYNC/default/900_copy_result_files.sh
  usr/share/rear/prep/RSYNC/GNU/Linux/200_selinux_in_use.sh
  usr/share/rear/prep/RSYNC/default/100_check_rsync.sh
  usr/share/rear/prep/RSYNC/default/150_check_rsync_protocol_version.sh
  usr/share/rear/restore/RSYNC/default/400_restore_rsync_backup.sh
  usr/share/rear/verify/RSYNC/default/550_check_remote_backup_archive.sh
Labels: enhancement, cleanup, blocker

#2819 Preparations for ReaR 2.7
  doc/rear-release-notes.txt
  doc/rear.8
  doc/rear.8.adoc
  packaging/debian/changelog
  packaging/rpm/rear.spec
  usr/sbin/rear
Labels: enhancement, waiting for info, blocker

#2839 Pass -y to lvcreate instead of piping the output of yes
  usr/share/rear/conf/GNU/Linux.conf
  usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh
Labels: enhancement, cleanup
