Repository rear/rear, pull requests merged in 2022-06, with the labels that each got.

#2815 Describe USB_BOOT_PART_SIZE and USB_DEVICE_BOOT_LABEL
  usr/share/rear/conf/default.conf
Labels: documentation, blocker

#2814 Replace 'RELAXRECOVER' in variable names
  usr/share/rear/lib/global-functions.sh
Labels: cleanup

#2816 RPM spec: update build requirement for Fedora to unblock Packit build and run make validate after build
  packaging/rpm/rear.spec
Labels: enhancement, ReaR Project

#2823 Update and extend Packit build targets
  .packit.yaml
Labels: enhancement, ReaR Project

#2822 Fix vi in the rescue system on Fedora and RHEL 9
  usr/share/rear/build/GNU/Linux/005_create_symlinks.sh
  usr/share/rear/build/OPALPBA/Linux-i386/106_remove_files_copied_unconditionally.sh
  usr/share/rear/conf/GNU/Linux.conf
Labels: enhancement, cleanup, blocker

#2827 Use fail-safe 'yes' pipe for "lvm lvcreate"
  usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh
Labels: enhancement, bug

#2828 Recognise `-b`/`--bios` options in `format` workflow
  usr/share/rear/lib/format-workflow.sh
Labels: bug
