Repository rear/rear, pull requests merged in 2022-02, with the labels that each got.

#2749 Add `console=tty0` to cmdline only if no real serial device was found
  usr/share/rear/lib/serial-functions.sh
Labels: bug

#2748 Include `dmsetup` and `dmeventd` unconditionally
  usr/share/rear/conf/GNU/Linux.conf
Labels: bug, cleanup

#2750 multipath: fix exclusion of still wanted devices
  usr/share/rear/layout/save/default/335_remove_excluded_multipath_vgs.sh
Labels: bug

#2736 New EXCLUDE_IP_ADDRESSES and EXCLUDE_NETWORK_INTERFACES directives
  usr/share/rear/conf/default.conf
  usr/share/rear/rescue/GNU/Linux/310_network_devices.sh
Labels: enhancement
