Repository rear/rear, pull requests merged in 2022-05, with the labels that each got.

#2797 Comment out remote space check with rsync #2760
  usr/share/rear/backup/RSYNC/default/450_calculate_req_space.sh
Labels: enhancement, minor bug

#2795 Verify file hashes at the end of recover after file restore from backup
  usr/share/rear/conf/default.conf
  usr/share/rear/finalize/GNU/Linux/250_migrate_disk_devices_layout.sh
  usr/share/rear/finalize/GNU/Linux/280_migrate_uuid_tags.sh
  usr/share/rear/finalize/default/060_compare_files.sh
  usr/share/rear/layout/save/default/490_check_files_to_patch.sh
  usr/share/rear/layout/save/default/600_snapshot_files.sh
Labels: enhancement

#2800 Use disklayout.conf keyword 'raidarray' instead of 'raid'
  doc/user-guide/06-layout-configuration.adoc
  usr/share/rear/layout/prepare/GNU/Linux/120_include_raid_code.sh
  usr/share/rear/layout/prepare/default/420_autoresize_last_partitions.sh
  usr/share/rear/layout/recreate/default/120_confirm_wipedisk_disks.sh
  usr/share/rear/layout/recreate/default/220_verify_layout.sh
  usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh
  usr/share/rear/lib/layout-functions.sh
Labels: cleanup, blocker

#2803 Ensure supported partition tables
  usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
Labels: enhancement, waiting for info

#2804 Ensure syntactically correct 'disk' and 'part' entries in disklayout.conf
  usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
Labels: enhancement, waiting for info

#2728 Always include loaded kernel modules
  usr/share/rear/build/GNU/Linux/400_copy_modules.sh
Labels: bug, blocker

#2791 For GRUB_RESCUE set 'root=/dev/ram0 vga=normal rw' as for other boot media
  usr/share/rear/output/default/940_grub2_rescue.sh
Labels: enhancement, bug

#2808 Exclude dev/watchdog* from recovery system
  usr/share/rear/conf/default.conf
Labels: enhancement

#2813 Update the ISO volume label in comments
  usr/share/rear/lib/global-functions.sh
  usr/share/rear/restore/NETFS/default/400_restore_backup.sh
  usr/share/rear/restore/YUM/default/410_restore_backup.sh
Labels: cleanup
