Repository rear/rear, pull requests merged in 2023-10, with the labels that each got.

#3052 Enable automated backup & recovery test in CI on PRs
  .fmf/version
  .packit.yaml
  tests/plans/backup-and-restore/main.fmf
  tests/plans/main.fmf
Labels: enhancement, ReaR Project

#3054 Fail safe USB_DEVICE_BOOT_LABEL setting and fallback
  usr/share/rear/output/USB/Linux-i386/300_create_grub.sh
Labels: enhancement, minor bug

#2961 Copy the console= kernel arguments from the original system
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/serial-functions.sh
  usr/share/rear/prep/GNU/Linux/200_include_serial_console.sh
  usr/share/rear/rescue/GNU/Linux/400_use_serial_console.sh
Labels: enhancement, cleanup, minor bug

#3057 Better explain apply_layout_mappings() implementation
  usr/share/rear/lib/layout-functions.sh
Labels: documentation
