Repository rear/rear, pull requests merged in 2023-07, with the labels that each got.

#3023 issue: #3018: remove $SESAM_WORK_DIR from excludes
  usr/share/rear/prep/SESAM/default/400_prep_sesam.sh
Labels: bug, external tool

#3027 Make sure rescue contains all COPY_AS_IS files
  usr/share/rear/build/GNU/Linux/100_copy_as_is.sh
Labels: bug

#3030 Update 200_check_usb_layout.sh
  usr/share/rear/format/USB/default/200_check_usb_layout.sh
Labels: enhancement
