Repository rear/rear, pull requests merged in 2023-12, with the labels that each got.

#3089 New RECOVERY_COMMANDS array
  usr/share/rear/conf/default.conf
  usr/share/rear/skel/default/etc/scripts/system-setup
Labels: enhancement

#3102 OUTPUT=USB: add a check that OUTPUT_URL is mounted
  usr/share/rear/output/USB/Linux-i386/105_check_mounted_usb.sh
Labels: enhancement

#3105 Do not touch $BUILD_DIR/outputfs (the backup location) during restore
  usr/share/rear/restore/NETFS/default/400_restore_backup.sh
Labels: cleanup

#3104 Error() instead of BugError() in 850_make_USB_bootable.sh
  usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh
Labels: enhancement

#3108 Set 'dmesg -n 5' in etc/scripts/boot
  usr/share/rear/skel/default/etc/scripts/boot
Labels: enhancement

#3110 Fixed 800_enforce_usb_output.sh
  usr/share/rear/build/USB/default/800_enforce_usb_output.sh
Labels: bug

#3111 Show BugError message arguments without single quotes
  usr/share/rear/lib/_input-output-functions.sh
Labels: cleanup

#3113 Set 'dmesg -n [4-6]' in new 'setup' script 007_set_dmesg_level.sh
  usr/share/rear/setup/default/007_set_dmesg_level.sh
Labels: enhancement
