Repository rear/rear, pull requests merged in 2023-04, with the labels that each got.

#2950 ReaR in Docker for development & fix package dependencies
  .github/workflows/build-packages.yml
  .gitignore
  Makefile
  doc/Makefile
  doc/user-guide/Makefile
  packaging/arch/PKGBUILD
  packaging/arch/PKGBUILD.local
  packaging/debian/control
  packaging/debian/rear.lintian-overrides
  packaging/debian/rules
  tools/run-in-docker
  tools/run-in-docker.bashrc
  usr/sbin/rear
  usr/share/rear/build/GNU/Linux/100_copy_as_is.sh
  usr/share/rear/build/default/970_add_rear_release.sh
  usr/share/rear/layout/prepare/default/550_finalize_script.sh
  usr/share/rear/lib/validated/Debian/10/i386.txt
  usr/share/rear/lib/validated/Debian/11/i386.txt
  usr/share/rear/lib/validated/SUSE_LINUX/15.3/i386.txt
  usr/share/rear/lib/validated/SUSE_LINUX/15/i386.txt
  usr/share/rear/lib/validated/Ubuntu/22.04/i386.txt
  usr/share/rear/lib/validated/Ubuntu/22.10/i386.txt
  usr/share/rear/skel/default/etc/init/start-serial.conf
  usr/share/rear/skel/default/etc/init/start-sshd.conf
  usr/share/rear/skel/default/usr/lib/systemd/system/plymouth-start.service
Labels: enhancement, ReaR Project

#2965 Add proper python support / fix GALAXY11-related issues
  packaging/debian/rear.lintian-overrides
  usr/share/rear/build/default/990_verify_rootfs.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/layout/save/GALAXY11/default/400_check_galaxy11_configuration.sh
  usr/share/rear/lib/checklayout-workflow.sh
  usr/share/rear/lib/mkboot-workflow.sh
  usr/share/rear/prep/default/390_include_python.sh
  usr/share/rear/rescue/GNU/Linux/990_sysreqs.sh
  usr/share/rear/restore/GALAXY11/default/400_restore_with_galaxy.sh
  usr/share/rear/verify/GALAXY11/default/420_login_to_galaxy_and_setup_environment.sh
  usr/share/rear/verify/GALAXY11/default/550_request_point_in_time_restore_parameters.sh
Labels: sponsored, Dedicated Priority Support

#2963 OBDR fixes
  usr/share/rear/output/OBDR/Linux-i386/820_create_iso_image.sh
  usr/share/rear/output/OBDR/default/840_write_image.sh
  usr/share/rear/prep/TAPE/default/400_check_tape_drive.sh
  usr/share/rear/skel/OBDR/etc/scripts/system-setup.d/43-init-cciss.sh
Labels: bug

#2878 Exclusions for Veritas
  usr/share/rear/conf/default.conf
Labels: enhancement, discuss / RFC

#2847 Add Shell linter - Differential-ShellCheck
  .github/dependabot.yml
  .github/workflows/differential-shellcheck.yml
Labels: enhancement, ReaR Project
