Repository rear/rear, pull requests merged in 2023-01, with the labels that each got.

#2903 Protect against colons in pvdisplay output
  usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh
Labels: enhancement

#2904 Install extlinux for OUTPUT=USB for a vfat boot partition
  usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh
Labels: enhancement

#2905 OUTPUT=USB: Use target=i386-pc for legacy BIOS GRUB2 install on EFI systems
  usr/share/rear/output/USB/Linux-i386/300_create_grub.sh
Labels: enhancement

#2910 Addendum for issue 2045 for Linux-ppc64le/660_install_grub2.sh
  usr/share/rear/finalize/Linux-ppc64le/660_install_grub2.sh
Labels: cleanup

#2915 Make get_serial_console_devices() fail-safe if no serial device node exists
  usr/share/rear/lib/serial-functions.sh
Labels: minor bug
