Repository rear/rear, pull requests merged in 2023-06, with the labels that each got.

#2988 Implement non-interactive mode
  README.adoc
  doc/rear.8.adoc
  usr/sbin/rear
  usr/share/rear/format/USB/default/300_format_usb_disk.sh
  usr/share/rear/layout/prep-for-mount/default/600_show_unprocessed.sh
  usr/share/rear/layout/prepare/GNU/Linux/150_include_drbd_code.sh
  usr/share/rear/layout/prepare/default/200_recreate_hpraid.sh
  usr/share/rear/layout/prepare/default/300_map_disks.sh
  usr/share/rear/layout/prepare/default/600_show_unprocessed.sh
  usr/share/rear/lib/_input-output-functions.sh
  usr/share/rear/lib/help-workflow.sh
  usr/share/rear/prep/default/040_check_backup_and_output_scheme.sh
  usr/share/rear/restore/BORG/default/300_load_archives.sh
  usr/share/rear/skel/default/etc/scripts/system-setup
  usr/share/rear/verify/CDM/default/430_gen_rbs_uuid_for_cdm.sh
  usr/share/rear/verify/GALAXY11/default/420_login_to_galaxy_and_setup_environment.sh
  usr/share/rear/verify/GALAXY11/default/500_select_backupset.sh
Labels: sponsored

#2998 Add fully automated restore to REQUESTRESTORE
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/filesystems-functions.sh
  usr/share/rear/restore/NFS4SERVER/default/400_restore_with_nfs_server.sh
  usr/share/rear/restore/REQUESTRESTORE/default/200_prompt_user_to_start_restore.sh
Labels: enhancement

#2991 ISO OUTPUT Improvements
  usr/share/rear/conf/default.conf
  usr/share/rear/output/default/950_copy_result_files.sh
Labels: enhancement

#2996 Add -f (force) option to wipefs command in 120_include_raid_code.sh
  usr/share/rear/layout/prepare/GNU/Linux/120_include_raid_code.sh
Labels: enhancement, discuss / RFC

#3006 New --expose-secrets option plus SECRET_OUTPUT_DEV
  usr/sbin/rear
  usr/share/rear/lib/_input-output-functions.sh
Labels: enhancement, critical / security / legal

#3019 issue: #3018: fix sesam default exlude pathes
  usr/share/rear/lib/sesam-functions.sh
  usr/share/rear/prep/SESAM/default/400_prep_sesam.sh
Labels: bug
