Repository rear/rear, pull requests merged in 2023-05, with the labels that each got.

#2973 nfs_server as new restore method
  doc/rear.8.adoc
  usr/share/rear/conf/default.conf
  usr/share/rear/prep/NFS4SERVER/default/400_prep_nfs_server.sh
  usr/share/rear/restore/NFS4SERVER/default/300_start_nfs_server.sh
  usr/share/rear/restore/NFS4SERVER/default/400_restore_with_nfs_server.sh
  usr/share/rear/restore/NFS4SERVER/default/500_stop_nfs_server.sh
  usr/share/rear/verify/NFS4SERVER/default/400_verify_nfs_server.sh
Labels: enhancement, sponsored

#2981 Increase USER_INPUT_INTERRUPT_TIMEOUT default from 10 to 30 seconds
  usr/share/rear/conf/default.conf
Labels: enhancement

#2982 Update default.conf
  etc/rear/local.conf
  usr/share/rear/conf/default.conf
Labels: cleanup

#2985 Do not leak the GALAXY11_PASSWORD value into the log file
  usr/share/rear/verify/GALAXY11/default/420_login_to_galaxy_and_setup_environment.sh
Labels: critical / security / legal

#2986 Do not leak the SSH_ROOT_PASSWORD value into the log file
  usr/share/rear/build/default/500_ssh_setup.sh
  usr/share/rear/rescue/default/500_ssh.sh
  usr/share/rear/restore/YUM/default/970_set_root_password.sh
  usr/share/rear/restore/ZYPPER/default/970_set_root_password.sh
Labels: critical / security / legal
