Repository rear/rear, pull requests merged in 2024-11, with the labels that each got.

#3345 Make sourcing DUPLY_PROFILE reasonably secure
  usr/share/rear/backup/DUPLICITY/default/500_make_duplicity_backup.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/global-functions.sh
  usr/share/rear/prep/DUPLICITY/default/200_find_duply_profile.sh
  usr/share/rear/prep/DUPLICITY/default/220_define_backup_prog.sh
  usr/share/rear/restore/DUPLICITY/default/110_check_temp_dir_with_duply.sh
  usr/share/rear/verify/DUPLICITY/default/250_check_duply_profile.sh
Labels: enhancement, bug, cleanup, critical / security / legal, blocker

#3171 Make OS detection from `/etc/os-release` more robust
  usr/share/rear/lib/config-functions.sh
  usr/share/rear/lib/framework-functions.sh
Labels: enhancement, bug, cleanup, blocker

#3344 Minor os-detection improvements
  usr/share/rear/lib/config-functions.sh
  usr/share/rear/rescue/GNU/Linux/310_network_devices.sh
Labels: enhancement, bug, waiting for info

#3347 Skip to add /.snapshots by default to the backup include list
  usr/share/rear/backup/NETFS/default/400_create_include_exclude_files.sh
Labels: enhancement

#3348 Call 'lsblk' with 'MOUNTPOINTS' to show all mounted btrfs subvolumes
  usr/share/rear/layout/save/GNU/Linux/100_create_layout_file.sh
Labels: enhancement

#3349 After doing lots of experiments with RAMdisks it is good to have some…
  usr/share/rear/conf/GNU/Linux.conf
  usr/share/rear/skel/default/etc/profile
Labels: enhancement, Dedicated Priority Support
