Repository rear/rear, pull requests merged in 2024-09, with the labels that each got.

#3307 Make .codespellignore ASCII
  .codespellignore
Labels: cleanup

#3306 Overhauled SLE11-SLE12-SAP-HANA-UEFI-example.conf
  usr/share/rear/conf/examples/SLE11-SLE12-SAP-HANA-UEFI-example.conf
Labels: enhancement, documentation, PR approved

#3281 conf: reintroduce `Linux-s390.conf`
  usr/share/rear/conf/Linux-s390.conf
  usr/share/rear/prep/Linux-s390/305_include_s390_tools.sh
Labels: enhancement, blocker

#3309 BACKUP=NSR: Deprecate 650_check_iso_recoverable.sh
  usr/share/rear/layout/save/NSR/default/650_check_iso_recoverable.sh
Labels: cleanup, external tool

#3312 #3178 improve USB device detection
  usr/share/rear/format/USB/default/200_check_usb_layout.sh
  usr/share/rear/format/USB/default/300_format_usb_disk.sh
Labels: enhancement

#3314 Request BIOS for backup and restore tests
  tests/plans/backup-and-restore/main.fmf
Labels: enhancement, ReaR Project
