Repository rear/rear, pull requests merged in 2024-07, with the labels that each got.

#3041 Reorder systemd units in the rescue system and make sure syslog is started
  usr/share/rear/skel/default/etc/event.d/automatic-rear
  usr/share/rear/skel/default/etc/event.d/tty1
  usr/share/rear/skel/default/etc/init/rcS.conf
  usr/share/rear/skel/default/etc/inittab
  usr/share/rear/skel/default/etc/scripts/run-automatic-rear
  usr/share/rear/skel/default/etc/scripts/system-setup
  usr/share/rear/skel/default/etc/scripts/system-setup-functions.sh
  usr/share/rear/skel/default/usr/lib/systemd/system/automatic-rear.service
  usr/share/rear/skel/default/usr/lib/systemd/system/getty@.service
  usr/share/rear/skel/default/usr/lib/systemd/system/multi-user.target
  usr/share/rear/skel/default/usr/lib/systemd/system/multi-user.target.wants/automatic-rear.service
  usr/share/rear/skel/default/usr/lib/systemd/system/network-online.target
  usr/share/rear/skel/default/usr/lib/systemd/system/network-online.target.wants/sysinit.service
  usr/share/rear/skel/default/usr/lib/systemd/system/rsyslog.service
  usr/share/rear/skel/default/usr/lib/systemd/system/run-system-setup.service
  usr/share/rear/skel/default/usr/lib/systemd/system/sysinit.service
  usr/share/rear/skel/default/usr/lib/systemd/system/sysinit.target
  usr/share/rear/skel/default/usr/lib/systemd/system/syslog.socket
Labels: enhancement, bug, cleanup

#3179 Migrate MAC addresses and interface names in NetworkManager keyfiles during network configuration migration
  usr/share/rear/finalize/GNU/Linux/320_migrate_network_configuration_files.sh
Labels: enhancement

#3175 Automatically include mounted btrfs subvolumes in NETFS backups
  usr/share/rear/layout/prepare/default/610_exclude_from_restore.sh
  usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
  usr/share/rear/layout/save/default/340_generate_mountpoint_device.sh
  usr/share/rear/lib/filesystems-functions.sh
Labels: enhancement

#3245 Avoid returning 1 from a script if all is OK
  usr/share/rear/output/ISO/Linux-i386/850_check_for_errors.sh
Labels: cleanup, minor bug

#3278 Autodetect secure boot via mokutil and guess the secure boot shim
  usr/share/rear/conf/default.conf
  usr/share/rear/prep/Linux-i386/370_detect_secure_boot.sh
Labels: enhancement
