Repository rear/rear, pull requests merged in 2024-06, with the labels that each got.

#3239 Fix version test in udev start by desupporting systemd < 190
  .packit.yaml
  usr/share/rear/build/GNU/Linux/600_verify_and_adjust_udev.sh
  usr/share/rear/skel/default/etc/scripts/system-setup.d/40-start-udev-or-load-modules.sh
Labels: bug, cleanup

#3246 Reenable CentOS Stream 8 CI builds and tests
  .packit.yaml
Labels: ReaR Project

#3244 Replace obsolete `egrep` with `grep -E`
  doc/user-guide/14-ZYPPER-and-YUM.adoc
  doc/user-guide/15-EFISTUB.adoc
  tests/setup1/verify.sh
  tools/run-in-docker.bashrc
  usr/share/rear/backup/YUM/default/600_capture_selinux_contexts.sh
  usr/share/rear/build/default/490_fix_broken_links.sh
  usr/share/rear/build/default/990_verify_rootfs.sh
  usr/share/rear/build/default/995_md5sums_rootfs.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/conf/examples/SLE12-SP1-btrfs-example.conf
  usr/share/rear/conf/examples/SLE12-SP2-btrfs-example.conf
  usr/share/rear/conf/examples/SLE12-btrfs-example.conf
  usr/share/rear/finalize/Fedora/550_rebuild_initramfs.sh
  usr/share/rear/finalize/GNU/Linux/250_migrate_disk_devices_layout.sh
  usr/share/rear/finalize/GNU/Linux/250_migrate_lun_wwid.sh
  usr/share/rear/finalize/GNU/Linux/260_rename_diskbyid.sh
  usr/share/rear/finalize/GNU/Linux/280_migrate_uuid_tags.sh
  usr/share/rear/finalize/GNU/Linux/320_migrate_network_configuration_files.sh
  usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
  usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh
  usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
  usr/share/rear/layout/save/GNU/Linux/260_crypt_layout.sh
  usr/share/rear/layout/save/GNU/Linux/270_hpraid_layout.sh
  usr/share/rear/layout/save/GNU/Linux/510_current_disk_usage.sh
  usr/share/rear/layout/save/default/490_check_files_to_patch.sh
  usr/share/rear/lib/_input-output-functions.sh
  usr/share/rear/lib/layout-functions.sh
  usr/share/rear/lib/linux-functions.sh
  usr/share/rear/lib/mkrescue-functions.sh
  usr/share/rear/lib/rsync-functions.sh
  usr/share/rear/prep/default/320_include_uefi_env.sh
  usr/share/rear/rescue/NETFS/default/610_save_capabilities.sh
  usr/share/rear/restore/BAREOS/default/400_restore_backup.sh
  usr/share/rear/restore/YUM/default/940_generate_fstab.sh
Labels: cleanup

#3254 Replace '/tmp/rear.XXX...' by '/var/tmp/rear.XXX...' in comments
  usr/share/rear/build/GNU/Linux/390_copy_binaries_libraries.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/layout/compare/default/500_compare_layout.sh
  usr/share/rear/output/ISO/Linux-i386/700_create_efibootimg.sh
  usr/share/rear/output/USB/Linux-i386/850_make_USB_bootable.sh
  usr/share/rear/output/default/950_copy_result_files.sh
  usr/share/rear/restore/NETFS/default/400_restore_backup.sh
Labels: cleanup

#3250 In 990_verify_rootfs.sh fix issue #3021
  usr/share/rear/build/default/990_verify_rootfs.sh
Labels: enhancement, minor bug

#3242 Fix IPv6 address support in OUTPUT_URL/BACKUP_URL
  usr/share/rear/backup/BLOCKCLONE/default/400_copy_disk_struct_files.sh
  usr/share/rear/backup/DUPLICITY/default/100_mount_duplicity_path.sh
  usr/share/rear/backup/DUPLICITY/default/980_unmount_duplicity_path.sh
  usr/share/rear/backup/NETFS/GNU/Linux/600_start_selinux.sh
  usr/share/rear/backup/NETFS/default/100_mount_NETFS_path.sh
  usr/share/rear/backup/NETFS/default/150_save_copy_of_prefix_dir.sh
  usr/share/rear/backup/NETFS/default/200_make_prefix_dir.sh
  usr/share/rear/backup/NETFS/default/250_create_lock.sh
  usr/share/rear/backup/NETFS/default/500_make_backup.sh
  usr/share/rear/backup/NETFS/default/970_remove_lock.sh
  usr/share/rear/backup/NETFS/default/980_umount_NETFS_dir.sh
  usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh
  usr/share/rear/layout/save/FDRUPSTREAM/Linux-s390/990_copy_disklayout_file.sh
  usr/share/rear/layout/save/default/310_autoexclude_usb.sh
  usr/share/rear/lib/_input-output-functions.sh
  usr/share/rear/lib/global-functions.sh
  usr/share/rear/lib/mkbackup-workflow.sh
  usr/share/rear/lib/rsync-functions.sh
  usr/share/rear/output/ISO/Linux-i386/810_prepare_multiple_iso.sh
  usr/share/rear/output/PXE/default/800_copy_to_tftp.sh
  usr/share/rear/output/PXE/default/801_copy_to_http.sh
  usr/share/rear/output/PXE/default/810_create_pxelinux_cfg.sh
  usr/share/rear/output/USB/Linux-i386/105_check_mounted_usb.sh
  usr/share/rear/output/default/100_mount_output_path.sh
  usr/share/rear/output/default/150_save_copy_of_prefix_dir.sh
  usr/share/rear/output/default/200_make_prefix_dir.sh
  usr/share/rear/output/default/250_create_lock.sh
  usr/share/rear/output/default/950_copy_result_files.sh
  usr/share/rear/output/default/970_remove_lock.sh
  usr/share/rear/output/default/980_umount_output_dir.sh
  usr/share/rear/prep/DUPLICITY/default/200_find_duply_profile.sh
  usr/share/rear/prep/DUPLICITY/default/210_check_NETFS_URL_requirements.sh
  usr/share/rear/prep/GNU/Linux/300_check_backup_and_output_url.sh
  usr/share/rear/prep/ISO/GNU/Linux/340_add_isofs_module.sh
  usr/share/rear/prep/NETFS/default/050_check_NETFS_requirements.sh
  usr/share/rear/prep/NETFS/default/070_set_backup_archive.sh
  usr/share/rear/prep/NETFS/default/400_automatic_exclude_recreate.sh
  usr/share/rear/prep/RBME/default/050_include_rbme_requirements.sh
  usr/share/rear/prep/RSYNC/default/100_check_rsync.sh
  usr/share/rear/prep/USB/default/060_set_usb_device.sh
  usr/share/rear/prep/default/030_translate_tape.sh
  usr/share/rear/prep/default/040_check_backup_and_output_scheme.sh
  usr/share/rear/restore/BLOCKCLONE/default/390_create_partitions.sh
  usr/share/rear/restore/NETFS/default/380_prepare_multiple_isos.sh
  usr/share/rear/restore/NETFS/default/400_restore_backup.sh
  usr/share/rear/restore/NETFS/default/500_selinux_autorelabel.sh
  usr/share/rear/restore/RBME/default/400_restore_backup.sh
  usr/share/rear/restore/YUM/default/410_restore_backup.sh
  usr/share/rear/verify/NETFS/default/050_start_required_nfs_daemons.sh
  usr/share/rear/verify/RBME/default/150_check_nobody_uid_nfs.sh
  usr/share/rear/verify/RBME/default/540_choose_backup.sh
  usr/share/rear/verify/USB/NETFS/default/540_choose_backup_archive.sh
Labels: enhancement, bug, cleanup

#3252 Reduce the matrix of CI runs: disable the Fedora rawhide and 40 tests, Koji scratch builds, openSUSE Copr builds
  .packit.yaml
Labels: ReaR Project
