Repository rear/rear, pull requests merged in 2024-05, with the labels that each got.

#3211 Typo fixes: BOOT_ON_SAN -> BOOT_OVER_SAN
  usr/share/rear/conf/examples/RHEL7-PPC64LE-Multipath-PXE-GRUB.conf
  usr/share/rear/layout/prepare/GNU/Linux/210_load_multipath.sh
Labels: minor bug

#3212 default.conf example for COPY_AS_IS_EXCLUDE_TSM
  usr/share/rear/conf/default.conf
Labels: enhancement, documentation

#3219 default.conf COPY_AS_IS_EXCLUDE_TSM example better explained
  usr/share/rear/conf/default.conf
Labels: documentation

#3221 Overhauled 400_create_include_exclude_files.sh
  usr/share/rear/backup/NETFS/default/400_create_include_exclude_files.sh
  usr/share/rear/backup/NETFS/default/500_make_backup.sh
Labels: enhancement, cleanup

#3224 default.conf add '/var/tmp/rear.*' to BACKUP_PROG_EXCLUDE
  usr/share/rear/conf/default.conf
Labels: enhancement

#3225 In sbin/rear make it clear when ReaR's TMP_DIR is used
  usr/sbin/rear
Labels: enhancement

#3220 Fix & improve snapshot release building & testing
  .github/workflows/build-packages.yml
  tools/run-in-docker
Labels: bug

#3229 Do not exclude '/var/tmp/rear.*' in default.conf
  usr/share/rear/conf/default.conf
Labels: bug

#3228 Set RECOVERY_MODE also in PORTABLE mode
  usr/sbin/rear
Labels: cleanup
