Repository rear/rear, pull requests merged in 2024-12, with the labels that each got.

#3351 fix: add -xdev option to find to avoid hanging NFS (#3350)
  usr/share/rear/lib/bootloader-functions.sh
Labels: bug

#3356 In 100_copy_as_is.sh error out if symlinking VAR_DIR SHARE_DIR fails
  usr/share/rear/build/GNU/Linux/100_copy_as_is.sh
Labels: bug

#3364 Fix some typos
  usr/share/rear/finalize/Linux-i386/630_install_grub.sh
  usr/share/rear/finalize/Linux-i386/660_install_grub2.sh
  usr/share/rear/layout/save/default/445_guess_bootloader.sh
Labels: documentation, minor bug

#3367 Schlomo prepare for release 2.8
  Makefile
  README.adoc
  README.md
  doc/rear.8
  doc/rear.8.adoc
  doc/user-guide/09-design-concepts.adoc
  packaging/gentoo/rear.ebuild
  packaging/rpm/rear.spec
  tools/run-in-docker
  usr/share/rear/conf/default.conf
Labels: enhancement, documentation, cleanup

#3370 WIP: ReaR 2.8 release preparations
  doc/rear-release-notes.txt
  doc/rear.8.adoc
  packaging/debian/changelog
  packaging/debian/rear.dsc
  packaging/rpm/rear.spec
  usr/sbin/rear
Labels: ReaR Project
