Repository rear/rear, pull requests merged in 2024-04, with the labels that each got.

#3177 New unique_unsorted() function
  usr/share/rear/backup/NETFS/default/500_make_backup.sh
  usr/share/rear/lib/global-functions.sh
Labels: enhancement

#3204 Better describe OUTPUT_PREFIX and NETFS_PREFIX
  usr/share/rear/conf/default.conf
Labels: documentation

#3182 #3067 use exit code of nc to check BACULA directory availability
  usr/share/rear/prep/BACULA/default/500_check_BACULA_bconsole_results.sh
Labels: minor bug, external tool
