Repository rear/rear, pull requests merged in 2024-03, with the labels that each got.

#3174 Allow 'shell' workflow in recovery system
  usr/share/rear/init/default/050_check_rear_recover_mode.sh
Labels: enhancement

#3158 docs: document booting of ReaR rescue initramfs on z/VM
  doc/user-guide/04-scenarios.adoc
Labels: enhancement, documentation

#3157 Remove hardcoded architecture-dependend strings from EFI code
  usr/share/rear/lib/uefi-functions.sh
  usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh
  usr/share/rear/output/ISO/Linux-i386/260_EFISTUB_populate.sh
  usr/share/rear/output/RAWDISK/Linux-i386/260_create_syslinux_efi_bootloader.sh
  usr/share/rear/output/RAWDISK/Linux-i386/270_create_grub2_efi_bootloader.sh
  usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
  usr/share/rear/output/default/940_grub2_rescue.sh
  usr/share/rear/prep/Linux-arm/330_set_efi_arch.sh
  usr/share/rear/prep/Linux-i386/330_set_efi_arch.sh
  usr/share/rear/prep/Linux-ia64/330_set_efi_arch.sh
  usr/share/rear/rescue/default/850_save_sysfs_uefi_vars.sh
Labels: enhancement, cleanup

#3176 Skip btrfs subvolumes when detecting ESP partitions
  usr/share/rear/finalize/Linux-i386/670_run_efibootmgr.sh
Labels: bug

#3183 Stale NFS detection in a very early stage #3109
  usr/share/rear/init/default/100_check_stale_nfs_mounts.sh
Labels: enhancement

#3168 Set TMPDIR to ReaR's TMP_DIR=$BUILD_DIR/tmp for programs that are called by ReaR
  usr/sbin/rear
  usr/share/rear/conf/default.conf
  usr/share/rear/prep/default/990_verify_empty_rootfs.sh
Labels: enhancement
