Repository rear/rear, pull requests merged in 2024-01, with the labels that each got.

#3124 Take AUTOEXCLUDE_PATH into account in layout doc
  doc/user-guide/06-layout-configuration.adoc
Labels: enhancement, documentation

#3123 Make initrd accessible only by root
  usr/share/rear/pack/GNU/Linux/900_create_initramfs.sh
Labels: critical / security / legal

#3131 Improve the description of AUTOEXCLUDE_PATH
  usr/share/rear/conf/default.conf
Labels: documentation

#3091 Let is_write_protected() report devices without device node as not write protected
  usr/share/rear/lib/write-protect-functions.sh
Labels: enhancement, bug, cleanup
