Repository rear/rear, pull requests merged in 2025-08, with the labels that each got.

#3500 In sbin/rear error out if '-c' is used in recovery system
  doc/rear.8
  doc/rear.8.adoc
  usr/sbin/rear
  usr/share/rear/lib/help-workflow.sh
Labels: enhancement, ready-to-merge?

#3498 Support some XFS features
  usr/share/rear/lib/filesystems-functions.sh
Labels: enhancement, fixed / solved / done

#3440 Add initial support for arm/aarch64 machines with UEFI
  packaging/rpm/rear.spec
  usr/share/rear/conf/default.conf
  usr/share/rear/finalize/Linux-arm/610_EFISTUB_run_efibootmgr.sh
  usr/share/rear/finalize/Linux-arm/670_run_efibootmgr.sh
  usr/share/rear/layout/save/default/445_guess_bootloader.sh
  usr/share/rear/output/ISO/Linux-arm/250_populate_efibootimg.sh
  usr/share/rear/output/ISO/Linux-arm/260_EFISTUB_populate.sh
  usr/share/rear/output/ISO/Linux-arm/700_create_efibootimg.sh
  usr/share/rear/output/ISO/Linux-arm/800_create_isofs.sh
  usr/share/rear/output/ISO/Linux-arm/810_prepare_multiple_iso.sh
  usr/share/rear/output/ISO/Linux-arm/820_create_iso_image.sh
  usr/share/rear/output/ISO/Linux-arm/830_create_iso_image_EFISTUB.sh
  usr/share/rear/output/USB/Linux-arm/100_create_efiboot.sh
  usr/share/rear/output/USB/Linux-i386/300_create_extlinux.sh
  usr/share/rear/output/USB/Linux-i386/300_create_grub.sh
  usr/share/rear/output/USB/default/105_check_mounted_usb.sh
  usr/share/rear/output/USB/default/200_make_usb_prefix_dir.sh
  usr/share/rear/output/USB/default/830_copy_kernel_initrd.sh
  usr/share/rear/prep/Linux-arm/060_check_config.sh
  usr/share/rear/prep/Linux-arm/370_detect_secure_boot.sh
  usr/share/rear/prep/USB/Linux-arm/350_safeguard_error_out.sh
  usr/share/rear/prep/USB/Linux-ppc64/350_safeguard_error_out.sh
Labels: enhancement
