Repository rear/rear, pull requests merged in 2025-01, with the labels that each got.

#3373 Update rear-release-notes.txt
  doc/rear-release-notes.txt
Labels: documentation, minor bug

#3382 Specify path to sbindir during RPM build
  packaging/rpm/rear.spec
Labels: enhancement, ReaR Project

#3380 Create /var/run symlink dynamically during mkrescue
  usr/share/rear/rescue/default/020_create_skeleton_dirs.sh
  usr/share/rear/skel/default/var/run
Labels: enhancement

#3387 Add 'timeout' to default REQUIRED_PROGS
  usr/share/rear/conf/default.conf
Labels: minor bug

#3389 2.9 release preparations
  doc/rear-release-notes.txt
  doc/rear.8.adoc
  packaging/debian/changelog
  packaging/debian/rear.dsc
  packaging/rpm/rear.spec
  usr/sbin/rear
Labels: ReaR Project
