Repository rear/rear, pull requests merged in 2025-04, with the labels that each got.

#3450 Set BACKUP_PROG_COMPRESS_OPTIONS as an empty array
  usr/share/rear/verify/OBDR/NETFS/default/540_set_backup_compression.sh
Labels: bug

#3449 Avoid that 001_verify_config_arrays.sh leaks secrets
  usr/share/rear/init/default/001_verify_config_arrays.sh
Labels: bug

#3452 run-in-docker: Use /lib64/ld-linux-x86-64.so.2 to detect HW architecture
  tools/run-in-docker
Labels: enhancement, ReaR Project

#3456 Add '-t cifs' in mount_url() in global-functions.sh
  usr/share/rear/lib/global-functions.sh
Labels: enhancement

#3455 EXCLUDE_COMPONENTS in 200_partition_layout.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
Labels: enhancement

#3462 Tell if 'use_lvmlockd = 1' in /etc/lvm/lvm.conf
  usr/share/rear/layout/prepare/GNU/Linux/110_include_lvm_code.sh
  usr/share/rear/layout/save/GNU/Linux/220_lvm_layout.sh
Labels: enhancement
