Repository rear/rear, pull requests merged in 2025-03, with the labels that each got.

#3418 ci: run Differential ShellCheck only on push to master
  .github/workflows/differential-shellcheck.yml
Labels: enhancement

#3408 New umount_mountpoint_retry_lazy function
  usr/share/rear/lib/global-functions.sh
  usr/share/rear/output/ISO/Linux-i386/700_create_efibootimg.sh
  usr/share/rear/output/USB/Linux-i386/100_create_efiboot.sh
Labels: enhancement

#3412 enhance 300_map_disks.sh script to also print the disk sizes
  usr/share/rear/layout/prepare/default/300_map_disks.sh
Labels: enhancement

#3420 ppc64le: Fix PReP Boot detection on GPT layouts
  usr/share/rear/layout/save/default/445_guess_bootloader.sh
Labels: enhancement, cleanup

#3415 On EL9 sshd will not start anymore #3413
  usr/share/rear/skel/default/etc/scripts/run-sshd
Labels: enhancement, bug

#3403 #3400 to avoid disks mounted without partition getting excluded
  usr/share/rear/layout/save/GNU/Linux/210_raid_layout.sh
  usr/share/rear/layout/save/default/305_uniq_disktodo.sh
  usr/share/rear/lib/layout-functions.sh
Labels: enhancement, minor bug

#3424 TRUSTED_OWNERS and TRUSTED_PATHS to protect against code injection via 'source'
  usr/sbin/rear
  usr/share/rear/conf/default.conf
  usr/share/rear/lib/_framework-setup-and-functions.sh
  usr/share/rear/lib/framework-functions.sh
Labels: severe improvement

#3419 Update CS and Fedora Images + add support for `podman`
  tools/run-in-docker
Labels: enhancement

#3435 Delete 800_enforce_usb_output.sh (deletes usr/share/rear/build/USB directory)
  usr/share/rear/build/USB/default/800_enforce_usb_output.sh
Labels: cleanup

#3437 Allow sourcing via dot in non-ReaR files
  usr/sbin/rear
  usr/share/rear/lib/_framework-setup-and-functions.sh
Labels: bug

#3432 remove zram swap from disklayout.conf
  usr/share/rear/layout/save/GNU/Linux/240_swaps_layout.sh
Labels: enhancement
