Repository rear/rear, pull requests merged in 2025-02, with the labels that each got.

#3393 Remove 040_inspect_configuration_files.sh (obsoleted by 001_verify_config_arrays.sh)
  usr/share/rear/prep/NETFS/default/040_inspect_configuration_files.sh
Labels: cleanup

#3399 Further enhance 880_check_for_mount_by_id.sh
  usr/share/rear/finalize/default/880_check_for_mount_by_id.sh
Labels: enhancement

#3402 #3401 discard longhorn devices
  usr/share/rear/layout/save/GNU/Linux/230_filesystem_layout.sh
Labels: bug

#3376 Using Blockclone to save a disk image of a RPi system
  doc/user-guide/12-BLOCKCLONE.adoc
  usr/share/rear/backup/BLOCKCLONE/default/500_start_clone.sh
  usr/share/rear/conf/default.conf
  usr/share/rear/conf/examples/blockclone.conf
  usr/share/rear/restore/BLOCKCLONE/default/400_restore_clone.sh
Labels: enhancement
