Repository rear/rear, pull requests merged in 2025-07, with the labels that each got.

#3484 BCF-5527: [Rear] Space in the variable device_to_be_wiped_size_bytes
  usr/share/rear/layout/recreate/default/150_wipe_disks.sh
Labels: enhancement

#3489 Use temporary LUKS password file in 160_include_luks_code.sh
  usr/share/rear/layout/prepare/GNU/Linux/160_include_luks_code.sh
Labels: bug

#3492 s390: remove the deprecated `OUTPUT=IPL` value
  usr/share/rear/prep/Linux-s390/034_check_config.sh
Labels: cleanup

#3494 BugError when AddExitTask QuietAddExitTask RemoveExitTask are called in subshell
  usr/share/rear/lib/_framework-setup-and-functions.sh
Labels: bug, ready-to-merge?

#3496 Get explicit user confirmation in opaladmin-workflow.sh
  usr/share/rear/lib/opaladmin-workflow.sh
Labels: bug, ready-to-merge?
